### ISSUE TITLE
[Feature Request]  Improve debug logging

### ISSUE THREAD

**Issue by toni-moreno** [soniah/gosnmp#109]
Debug log are  important to us to debug snmp issues with our devices.

But It leaks for two important things.

1. __Timestamps__
As @tardoe, suggest us . Would be great if gosnmp could add timestamp for each received data packed.  related with ( https://github.com/toni-moreno/snmpcollector/issues/240)

2.  __Packet sent debug__.
Current debug contains only received packet data, but as you can see in  the already closed issue  (https://github.com/soniah/gosnmp/issues/106) the complete debug can not be done if we can not see sent data to the device also.
 
Thank you very much

**Comment by soniah** [comment]
Hi Toni,

(also referencing https://github.com/toni-moreno/snmpcollector/issues/240).

For (1) timestamps are you asking for the timestamps to be put in (a) the logging or (b) the actual data returned to the client? (your program).

For (a) you could implement your own logger that satisfies the interface, and put in your own timestamps (and/or you could use other logging libraries that add colours, etc)

For (b) are you thinking about another field in SnmpPacket? If so, would you mind sketching out your ideas in a branch? Doesn't have to work, just gives me some ideas.

For (2) packet sent debug. Hmmm... , let me think on this for a while...

**Comment by toni-moreno** [comment]
Hi @soniah thanks for your feedback. 

For 1) I'm asking about only logging so as you have suggested  I will test with a new logger then.

For 2)  I built some weeks ago a gosnmp fork with extended packet send debugging that help us to fix  a Cisco ASA bug (https://github.com/soniah/gosnmp/issues/106#issuecomment-308479919) In the issue you can see the debug level . And I have done a PR now if you wish to watch the changes I've done in the  code at (https://github.com/soniah/gosnmp/pull/114).

If you like it , I can rebase the PR  to resolve conflicts or you can use as a first approach to a new debug system if you prefer. What do you prefer?

**Comment by soniah** [comment]
Would you mind doing a rebase? :-D

**Comment by toni-moreno** [comment]
Thank you very much @soniah @wdreeveii for the debug improvement!
