### ISSUE TITLE
Does setting Gauge32 works? Because the readme says yes.

### ISSUE THREAD

**Issue by jisuskraist** [soniah/gosnmp#110]
I tried to do a set with Gauge32 and an error popped saying that is not supported by the library.

I dug into the library and the code to marshal the PDU is there, but there's a case checking if the type is OctectString or Integer. Adding Gauge32 to the case made it work.

My question is: is this due to some unexpected behaviour when marshaling this kind of type ? Or can I fork the lib and make those changes safely ?

**Comment by soniah** [comment]
Fork and add a PR. From memory it wasn't added as I didn't have a test case -  please also add one.

**Comment by soniah** [comment]
Closed, thanks.
