### ISSUE TITLE
Logger interface only first value printed

### ISSUE THREAD

**Issue by leemcloughlin** [soniah/gosnmp#111]
Hi

First thanks for writing this library its so helpful!

I was getting these in my logs when using the Logger interface:

`Retry number [1 842351671104]. Last error was: %!v(MISSING)
`

In marshal.go in the the calls to `x.Logger.Print` and `x.Logger.Printf` are passing `v` where they need to pass `v...`

`x.Logger.Print(v...)`

`x.Logger.Printf(format, v...)`

**Comment by soniah** [comment]
Thanks for that! I've fixed the issue
