### ISSUE TITLE
Tests are failing

### ISSUE THREAD

**Issue by nmailhot** [soniah/gosnmp#112]
+ go test github.com/soniah/gosnmp/
--- FAIL: TestGenericFailureUnknownHost (0.00s)
        generic_e2e_test.go:175: Expected connection error of type 'no such host'! Got => Error establishing connection to host: dial udp: lookup gosnmp-test-unknown-host-1505156748863993309 on 127.0.0.1:53: read udp 127.0.0.1:48464->127.0.0.1:53: read: connection refused
--- FAIL: TestGenericFailureConnectionTimeout (0.00s)
        generic_e2e_test.go:187: Did not expect connection error with IP address
FAIL
FAIL    github.com/soniah/gosnmp        0.055s

Installed:
  golang.x86_64 0:1.7.4-1.el7

Dependency Installed:
  golang-bin.x86_64 0:1.7.4-1.el7                                           golang-src.noarch 0:1.7.4-1.el7

**Comment by wdreeveii** [comment]
You need to install a snmpd.

**Comment by nmailhot** [comment]
ok, so the tests require a running snmp server? with a specififc conf or anything wil do?

**Comment by nmailhot** [comment]
However if I read the message correctly the code expected a specific error and got another, so the test error handling seems broken.

**Comment by soniah** [comment]
Hi, I've pushed a fix to branch112, @nmailhot would you mind confirming you get the desired error message?

**Comment by soniah** [comment]
No response, closing.
