### ISSUE TITLE
WalkAll/BulkWalkAll return NoSuchName/NoSuchObject pdu if object doesn't exist

### ISSUE THREAD

**Issue by brian-brazil** [soniah/gosnmp#115]
The `walk` function falls back to using `getToWalk` if the returned pdu is outside the provided prefix. If however the requested prefix has no values at all, and v2 or v3 is in use this results in no error being returned in the PDU however NoSuchInstance/NoSuchObject will be returned in the variable binding, which is then returned to the user.

This is incorrect behaviour for a walk, this resulting pdu should be filtered.

**Comment by wdreeveii** [comment]
Ack, this is tied with issue #93. Working on a fix now.

**Comment by soniah** [comment]
Thanks @wdreeveii for stepping up. And thanks @brian-brazil for submitting the issue 🥇

**Comment by wdreeveii** [comment]
Hi @brian-brazil,

I believe recent fix for #93 also fixes this issue. Can you confirm?

**Comment by wdreeveii** [comment]
I think that is only a half-fix. It will not return NoSuchObject, NoSuchInstance in the PDU, but it also will not return an error for such cases. Would you like to see an error returned describing this NoSuchObject/NoSuchInstance?

**Comment by brian-brazil** [comment]
> I believe recent fix for #93 also fixes this issue. Can you confirm?

I think that fixes it thanks. I'll need to vendor in your change and get my customer to verify.

>  It will not return NoSuchObject, NoSuchInstance in the PDU, but it also will not return an error for such cases. Would you like to see an error returned describing this NoSuchObject/NoSuchInstance?

I would not like to see such an error, that's why I filed this bug. A Walk shouldn't return NoSuchObject/NoSuchInstance, it should return no PDUs.

**Comment by brian-brazil** [comment]
My customer has reported back that this isn't working, it looks like https://github.com/soniah/gosnmp/commit/c8049ff1ecad68b5c464bb12761afb5a538934a4 broke this again. 

A GetNext cannot return NoSuchObject or NoSuchInstance. Similarly it's not possible for BulkGet to return NoSuchInstance/NoSuchObject - this code is returning one from BulkWalkAll due to the Get. I would also argue that for consistency between v1 and v2, that the GetNext v1 NoSuchInstance not be treated as an error as v2 does not return an error in that case. 
Accordingly I think everything bar the fixing of the continue label should be reverted. None of these are actually errors.

**Comment by wdreeveii** [comment]
Alright, thank you for your input. Those errors will no longer be emitted.

**Comment by soniah** [comment]
Thanks @wdreeveii for all your work on this, and thanks @brian-brazil for submitting the bug.

**Comment by brian-brazil** [comment]
I've confirmation that this is working now. Thanks!
