### ISSUE TITLE
Support for sending SNMP v1 Traps

### ISSUE THREAD

**Issue by patrox** [soniah/gosnmp#121]
I was looking for a possiblity to send SNMP v1 Traps, but unfortunately `SendTrap` function doesn't support it: https://github.com/soniah/gosnmp/blob/master/trap.go#L30-L36.

According to: http://www.tcpipguide.com/free/t_SNMPVersion1SNMPv1MessageFormat-3.htm
the SNMP message format for V1 is quite simple, so supporting it shouldn't be too difficult either.

Is it possible to add this support ? With some guidance I could work on a PR, but first I would like to make sure that there are no issues with adding it.

@soniah, @wdreeveii What do you think about it ?

**Comment by soniah** [comment]
Thanks Patrick, I hadn't realized v1 supported traps.

Would you mind having a go at writing a PR? Since you're working with v1
traps at the moment, it will be much easier for you to verify that they
work.

Thanks, Sonia.

**Comment by patrox** [comment]
Sure thing, I actually have the changes ready, but now I need to clean up the code a bit and add some tests to verify that it behaves as expected.

**Comment by patrox** [comment]
@soniah The code was cleaned up and I already created a PR with the changes: https://github.com/soniah/gosnmp/pull/123.

I'll add some tests this evening, but could you please have a look at the change and give me some initial feedback ?

**Comment by soniah** [comment]
Hey @patrox I've rebased all this, fixed authorship. Thanks for all your work!
