### ISSUE TITLE
Timeout with non default settings

### ISSUE THREAD

**Issue by ChaosDIV** [soniah/gosnmp#125]
I get 5000-6000 records from switch and get timeout with non default settings like this:
```
params := &gosnmp.GoSNMP{
		Target:    target,
		Port:      161,
		Community: community,
		Version:   gosnmp.Version2c,		
		Timeout: time.Duration(10) * time.Second,		
}
err := params.Connect()
if err != nil {		
	log.Printf("Connect() err: %v", err)	
}
defer params.Conn.Close()
results, err = params.BulkWalkAll(oid)

Output:
#  Request timeout (after 0 retries)
```
but this code, have not errors and work fine:
```
gosnmp.Default.Target = target
gosnmp.Default.Community = community
gosnmp.Default.Timeout = time.Duration(10 * time.Second) // Timeout better suited to walking
err := gosnmp.Default.Connect()
if err != nil {
   fmt.Printf("Connect err: %v\n", err)			
}
defer gosnmp.Default.Conn.Close()
results, err = gosnmp.Default.BulkWalkAll(oid)
```

**Comment by soniah** [comment]
Version:   gosnmp.Version2c,	

??

**Comment by ChaosDIV** [comment]
I don`t understand your question.
"Version:   gosnmp.Version2c,"  i got it from your example2.   What`s wrong?
With snmpwalk:   snmpwalk -v2c.

I thought maybe it happened because i  use gorutines, but i`m rewrite my code without gorutines - and have same result.

**Comment by wdreeveii** [comment]
Can you please try your test again, but this time providing a Retries parameter with value > 0?

**Comment by ChaosDIV** [comment]
Hello, I try 
Retries:   3,
And it`s work fine. Thank you very much.

full conf:
params := &gosnmp.GoSNMP{		
		Target:    target,
		Port:      161,
		Community: community,
		Version:   gosnmp.Version2c,
		Retries:   3,		
		Timeout: time.Duration(10) * time.Second,		
	}
