### ISSUE TITLE
Feature request: option to not check returned OIDs are increasing

### ISSUE THREAD

**Issue by mitchellrj** [soniah/gosnmp#132]
Like `snmpwalk -Cc`. Useful for some situations.

**Comment by soniah** [comment]
Thanks! I'll have a look when summer holidays finish ;-)

**Comment by soniah** [comment]
@mitchellrj would you mind making a suggestion of where I would make this change in the code? Thanks, Sonia.

**Comment by soniah** [comment]
My notes, reading through the code at $WORK

Looks like I can just add another field to type GoSNMP around line gosnmp.go:80
```
walk.go:78 "OID not increasing" in :12 walk()

// Save last oid for next request   <<===
walk.go:86 oid = response.Variables[len(response.Variables)-1].Name

:39 case GetNextRequest: ... GetNext() XX
:21 oid := rootOid   XX
:13,14 rootOid == "", etc.. rootOid = baseOid XX

gosnmp.go
:30 baseOid = ".1.3.6.1.2.1" XX
```

My notes from net-snmp:
```
% man snmpwalk
"snmpwalk is an SNMP application that uses SNMP GETNEXT requests"

apps/snmpwalk.c:348 ->
apps/snmpwalk.c:292
(293:netsnmp_ds_get_boolean() - ignore)

% vim `grep -rl NETSNMP_DS_WALK_DONT_CHECK_LEXICOGRAPHIC *`
apps/snmpbulkwalk.c:129,197, etc - app opts parsing, setup
apps/snmpwalk.c - ditto

% grep -r -B 3 snmp_oid_compare *  # -> get editor setup to find definition :-(
```







```

**Comment by soniah** [comment]
I've added branch [132_oids_incr](https://github.com/soniah/gosnmp/tree/132_oids_incr).

However this may be more complex that I first thought - see TODO [walk.go:78](https://github.com/soniah/gosnmp/blob/132_oids_incr/walk.go#L78). In which case I'll be leaving this for a while, I have other projects to work on.

In the meantime, would you mind checking out this branch and using it with your devices?

**Comment by soniah** [comment]
Closing. I'll wait for a PR from others or fix it when I have more time.

`ours` merge done to keep history - 1c893d7c4a8476ef8521c2edd7d0a85f282e589a

**Comment by soniah** [comment]
re-opening as enhancement

**Comment by soniah** [comment]
I've made an attempt at implementing this - see branch https://github.com/soniah/gosnmp/tree/issue132

EXPERIMENTAL; feedback welcome (good or bad).

**Comment by soniah** [comment]
Fixed with commit https://github.com/soniah/gosnmp/commit/ea8c875f6b1fd364ae84e6e06333eee11947daa9 💯
