### ISSUE TITLE
Quote 1.10 in Travis file

### ISSUE THREAD

**Issue by lfkeitel** [soniah/gosnmp#141]
Due to the way YAML is parsed, 1.10 is parsed as the float number 1.1, not the string "1.10". You need to quote it to use Go 1.10. Right now, you're testing against Go 1.1 through 1.9.

https://github.com/soniah/gosnmp/blob/master/.travis.yml#L12

https://docs.travis-ci.com/user/languages/go#Specifying-a-Go-version-to-use

**Comment by soniah** [comment]
Fixed! Thank you 💯
