### ISSUE TITLE
Build fails on 32 bit arch with constant overflows int error

### ISSUE THREAD

**Issue by danielnelson** [soniah/gosnmp#142]
When I try to build on a 32 bit architecture such as linux/386 or windows/386 I get an error:
```
$ GOARCH=386 go test -v -tags marshal
# github.com/soniah/gosnmp
./helper.go:365:31: constant 4294967295 overflows int
./helper.go:366:26: constant 4278190080 overflows int
FAIL    github.com/soniah/gosnmp [build failed]
```

I assume it was introduced in #134

**Comment by soniah** [comment]
Let me investigate if I need to revert 8e4e8b46cf4e6ba7340ce54175928533855b13bf or make other fixes. Thanks Daniel.

**Comment by soniah** [comment]
Hi Daniel, I've updated travis to test across 32 & 64, linux and windows. Tests aren't failing, can you give me some more details about the failure you're getting?

https://travis-ci.org/soniah/gosnmp/builds/362497479

**Comment by apetruhin** [comment]
soniah, it seems like GOARCH ignored - https://github.com/travis-ci/travis-ci/issues/6126
please check out build raw output - https://api.travis-ci.org/v3/job/362497505/log.txt
```
...
$ go env
GOARCH="amd64"
...
```

**Comment by soniah** [comment]
I've pushed a new travis config, let's see what happens. Dinner time here..

**Comment by soniah** [comment]
[Bamm](https://travis-ci.org/soniah/gosnmp/jobs/362587180)! we got a failure. Good, now I can bisect, error is probably that int32 stuff from a few days ago.

In the meantime probably a good idea to checkout an earlier commit :-)

**Comment by soniah** [comment]
I reverted the int32 stuff in a branch called `142_breaking32-3` but it's still failing (https://travis-ci.org/soniah/gosnmp/builds/362654499)

So I'm winding back further on `142_breaking32-4-bisect` and I'll start adding back in commits.

**Comment by soniah** [comment]
I wound back a long way in a branch called `` bit 32 builds still fail https://travis-ci.org/soniah/gosnmp/builds/362667521

So seems 32 bit hasn't worked for a long time, I'll put a note on the front page, this is going to take a bit of effort.

**Comment by brian-brazil** [comment]
This is https://github.com/soniah/gosnmp/commit/8e4e8b46cf4e6ba7340ce54175928533855b13bf.

We've been building 32bit for the snmp_exporter for a long time, this is a recent breakage.

**Comment by soniah** [comment]
@brian-brazil said "We've been building 32bit for the snmp_exporter for a long time, this was okay as of [f15472a](https://github.com/soniah/gosnmp/commit/f15472a4cd6f6ea7929e4c7d9f163c49f059924f) in February so this is likely a recent breakage."

**Comment by soniah** [comment]
Well this is odd, I can't see how these previous builds were actually working. Anyway, I'll just have to dig in and fix stuff.

* rewind branch [142_1_zamedic](https://github.com/soniah/gosnmp/tree/142_1_zamedic)
* travis fails https://travis-ci.org/soniah/gosnmp/builds/363117756

---

* even earlier rewind branch [142_2_mschoch](https://github.com/soniah/gosnmp/tree/142_2_mschoch)
* travis fails https://travis-ci.org/soniah/gosnmp/builds/363119150

---

* further rewind branch [142_3_pietv](https://github.com/soniah/gosnmp/tree/142_3_pietv)
* travis fails https://travis-ci.org/soniah/gosnmp/builds/363125599

---

(need to search on `go env` to see that GOARCH is being set correctly, at the second invocation)

**Comment by brian-brazil** [comment]
We only build the gosnmp code, we don't run your tests.

**Comment by brian-brazil** [comment]
I imagine that the vast majority of our users are using 64bit binaries. v3 use is reasonably common. I've sent a PR for one issue.

**Comment by soniah** [comment]
[Build is passing](https://travis-ci.org/soniah/gosnmp/builds/363164364), thank you for all your help Brian and @danielnelson

There's that little bug note at the very end of atomic, I wouldn't have thought to look.

> On both ARM and x86-32, it is the caller's responsibility to arrange for 64-bit alignment of 64-bit words accessed atomically. The first word in a variable or in an allocated struct, array, or slice can be relied upon to be 64-bit aligned.

That's nice, "first word in a struct".
