### ISSUE TITLE
Giving secretKey and privacyKey as input to UsmSecurityParameters struct from the client code

### ISSUE THREAD

**Issue by merinjo** [soniah/gosnmp#149]
Hi,

I need to do an snmpwalk with AuthPriv security enabled. For some reason I need to input the secretKey and privacyKey as HEX bytes but I am not able to do that in the current version of the library. The secretKey and privacyKey variables declared in UsmSecurityParameters struct in v3_usm.go are not accessible from outside. Is there any other way to input these values or is it possible to change the code to input them ?

My sample snmpwalk command is as below : 
 snmpwalk -v3 -u user -a MD5 -3k 0xaabbccdd1234 -x DES -3K 0xaabbccdd1234dcab -l authPriv udp6:host oid

**Comment by sh2244** [comment]
ACK

**Comment by soniah** [comment]
@wdreeveii ?

**Comment by soniah** [comment]
See also https://github.com/soniah/gosnmp/pull/160

**Comment by merinjo** [comment]
I have gone through the PR #160 but that was not what I had wanted to add in.

**Comment by merinjo** [comment]
If you see this struct - 
type UsmSecurityParameters struct {
	// localAESSalt must be 64bit aligned to use with atomic operations.
	localAESSalt uint64
	localDESSalt uint32

	AuthoritativeEngineID    string
	AuthoritativeEngineBoots uint32
	AuthoritativeEngineTime  uint32
	UserName                 string
	AuthenticationParameters string
	PrivacyParameters        []byte

	AuthenticationProtocol SnmpV3AuthProtocol
	PrivacyProtocol        SnmpV3PrivProtocol

	AuthenticationPassphrase string
	PrivacyPassphrase        string

	secretKey  []byte
	privacyKey []byte

	Logger Logger
}
These variables secretKey, privacyKey are not exposed outside the library. My snmpwalk requires me to directly input these two parameters rather than the passphrase.

**Comment by soniah** [comment]
@merinjo I'm closing this; you're welcome to submit a PR in which case I'll open the issue and review the PR. Thanks!

**Comment by merinjo** [comment]
I created a PR for this change

**Comment by merinjo** [comment]
PR 187
