### ISSUE TITLE
Please tag new release

### ISSUE THREAD

**Issue by dswarbrick** [soniah/gosnmp#151]
Please consider tagging a new release. The last release was tagged over three years ago.
I am going to package gosnmp for Debian (https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=840759), and starting with a 3+ year old tag with hundreds of commits piled on top is a not a nice way to start.

Also a minor nitpick - whilst adding the license to the golang-github-soniah-gosnmp package, I noticed what appears to be a typo:
```
Copyright 2012 Andreas Louca, 2012-2108 Sonia Hamilton.
```
I don't think you intend to copyright it for the next 90 years.

**Comment by soniah** [comment]
Thanks Daniel for stepping up and packaging GoSNMP - I know it can be lot of work. I had a look at the tags, `v1.9-memory` is the last one, very old as you say. What would you suggest for tagging, what would help you? `v.10`? Current status of project is occasional bug fixes and feature requests. So semantically it's not a `v2.x`.

I'll fix up the Copyright `;-)`. I don't know if I should keep updating this every year, or just put it a few years into the future. Any suggestions?

**Comment by dswarbrick** [comment]
If you feel that it is not yet at v2.x stage, just tag v1.10, since most distros' version parsing will consider this a later release than v1.9. It would also make things a bit simpler if you would drop the "-foo" suffix from future versions, since this gets a bit fiddly in the debian/watch file to handle these.

As far as the copyright - I Am Not A Lawyer - but generally people just update it from time to time if they are still actively working on the project. Unless you're making millions from this software, I don't think you need to guard your IP with up-to-the minute copyright notices. Besides, it's an excuse to tag at least one release per year ;-)

**Comment by soniah** [comment]
Thanks Daniel, I've tidied the copyright and tagged as v1.10. Pleae let me know if I can help you in any other way `:-)`

**Comment by dswarbrick** [comment]
A small followup - gosnmp package has been accepted into Debian unstable: https://tracker.debian.org/pkg/golang-github-soniah-gosnmp

**Comment by soniah** [comment]
Thank you very much!!

**Comment by nemith** [comment]
Please consider semver tagging (i.e 1.10.0) for the next release) for vgo support.

**Comment by soniah** [comment]
👍
