### ISSUE TITLE
ipv6 testing is failing

### ISSUE THREAD

**Issue by soniah** [soniah/gosnmp#155]
See `.travis.yml` and `snmp_users.sh`

**Comment by FuzzyStatic** [comment]
Will this fix the following?

```
Error establishing connection to host: dial udp [<redacted>]:161: connect: cannot assign requested address
```

**Comment by soniah** [comment]
I don't think so. Easiest way to find out is wind back gosnmp a few commits, to before the new ipv4/6 stuff. Let me know how you go :-)

**Comment by FuzzyStatic** [comment]
Looks like my issues is with Docker.

**Comment by soniah** [comment]
👍
