### ISSUE TITLE
SNMPv3

### ISSUE THREAD

**Issue by soniah** [soniah/gosnmp#16]
Implement snmpv3

**Comment by wdreeveii** [comment]
I have completed support for SNMPV3 as defined by rfc2574. https://www.ietf.org/rfc/rfc2574.txt

This includes MD5 and SHA authentication and DES encryption. I have made allowances for implementing AES encryption as defined in rfc3826. https://www.rfc-editor.org/rfc/rfc3826.txt

I see no need to delay for rfc3826 because there is very little chance the API will change any further, and this enhancement can be merged in at a later date.

Please have a look at the code and let me know how I can get this merged.

For reference the repository is located here: https://github.com/wdreeveii/gosnmp-sonia

Note: I had to disable an unmarshal test because unmarshal needs access to the UsmSecurityParameters struct in order to decode an encrypted packet. I'm looking for advice on how to reimplement this test with this new constraint.

**Comment by soniah** [comment]
Thanks Whitham, that's great! This is going to take a few days/a while
to merge... Let me have a look.

Sonia.

On Mon, Feb 9, 2015, at 09:31, Whitham D. Reeve II wrote:
> I have completed support for SNMPV3 as defined by rfc2574.
> https://www.ietf.org/rfc/rfc2574.txt

> This includes MD5 and SHA authentication and DES encryption. I have
> made allowances for implementing AES encryption as defined in rfc3826.
> https://www.rfc-editor.org/rfc/rfc3826.txt

> I see no need to delay for rfc3826 because there is very little chance
> the API will change any further, and this enhancement can be merged in
> at a later date.

> Please have a look at the code and let me know how I can get
> this merged.

> For reference the repository is located here:
> https://github.com/wdreeveii/gosnmp-sonia

> Note: I had to disable an unmarshal test because unmarshal needs
>       access to the UsmSecurityParameters struct in order to decode an
>       encrypted packet. I'm looking for advice on how to reimplement
>       this test with this new constraint.

> —
>
Reply to this email directly or view it on GitHub[1].



Links:

  1. https://github.com/soniah/gosnmp/issues/16#issuecomment-73436267

**Comment by wdreeveii** [comment]
For reference, I have included below the users/passwords necessary for tests against 'gosnmp-test-host' to work (net-snmp snmpd).

createUser noAuthNoPrivUser
createUser authOnlyUser  MD5 testingpass0123456789
createUser authOnlyUsersha SHA testingpass9876543210
createUser authPrivUser MD5 testingpass9876543210 DES

rouser   noAuthNoPrivUser noauth
rouser   authOnlyUser auth
rouser   authOnlyUsersha auth
rouser   authPrivUser authPriv

**Comment by soniah** [comment]
Thanks Witham. It's Monday here in Australia, so it might be a few days
or the weekend until I get onto things - you know what Mondays are like
:-) Sonia.

On Mon, Feb 9, 2015, at 12:10, Whitham D. Reeve II wrote:
> For reference, I have included below the users/passwords necessary for
> tests against 'gosnmp-test-host' to work (net-snmp snmpd).

> createUser noAuthNoPrivUser
>
createUser authOnlyUser MD5 testingpass0123456789
>
createUser authOnlyUsersha SHA testingpass9876543210
>
createUser authPrivUser MD5 testingpass9876543210 DES

> rouser noAuthNoPrivUser noauth
>
rouser authOnlyUser auth
>
rouser authOnlyUsersha auth
>
rouser authPrivUser authPriv

> —
>
Reply to this email directly or view it on GitHub[1].



Links:

  1. https://github.com/soniah/gosnmp/issues/16#issuecomment-73444555

**Comment by soniah** [comment]
Hi Whit,

I had a spare 5 mins, so I've started merging your stuff. Since there's
quite a few changes I'm using meld and looking at the differences, but
marking the git commits with your authorship. I've got a couple of
questions marked 'WHIT'.

I'm pushing to the branch https://github.com/soniah/gosnmp/tree/whit.
I've done all files except marshal.go, which I'm still working through.
Then I'll look at getting the commented out test going, and encrypt your
passwords and put them into the travis tests.

S.

On Mon, Feb 9, 2015, at 09:31, Whitham D. Reeve II wrote:
> I have completed support for SNMPV3 as defined by rfc2574.
> https://www.ietf.org/rfc/rfc2574.txt

> This includes MD5 and SHA authentication and DES encryption. I have
> made allowances for implementing AES encryption as defined in rfc3826.
> https://www.rfc-editor.org/rfc/rfc3826.txt

> I see no need to delay for rfc3826 because there is very little chance
> the API will change any further, and this enhancement can be merged in
> at a later date.

> Please have a look at the code and let me know how I can get
> this merged.

> For reference the repository is located here:
> https://github.com/wdreeveii/gosnmp-sonia

> Note: I had to disable an unmarshal test because unmarshal needs
>       access to the UsmSecurityParameters struct in order to decode an
>       encrypted packet. I'm looking for advice on how to reimplement
>       this test with this new constraint.

> —
>
Reply to this email directly or view it on GitHub[1].



Links:

  1. https://github.com/soniah/gosnmp/issues/16#issuecomment-73436267

**Comment by wdreeveii** [comment]
Can you merge the remaining (recent) changes? At first glance all the changes look good.
I would like to give golint a try.

All the tests pass with the current state of my repository. I would like to merge your changes into mine so that we are testing the same code and can hopefully narrow down the possibilities for the failing tests.

Does this work for you?

snmpwalk -v 3 -u authPrivUser -l authPriv -A testingpass9876543210 -x DES -X testingpass9876543210 gosnmp-test-host .1.3.6.1.2.1.1.1.0

**Comment by wdreeveii** [comment]
It seems go has dispensed with underscores :(

**Comment by wdreeveii** [comment]
I'm signing off for now - It's still Sunday and Monday is just around the corner. I really appreciate your efforts Sonia. Sorry for using so many commits, maybe I should have rebased before bringing it up.  I will make the code pass golint in the morning. Then we can let it bake for a while. I will test this on a few devices on our network and fix problems as they come.

**Comment by soniah** [comment]
No that's not working, but my test host is an old printer that probably
doesn't support snmpv3.

On Mon, Feb 9, 2015, at 19:03, Whitham D. Reeve II wrote:
> Can you merge the remaining (recent) changes? At first glance all the
> changes look good.
>
I would like to give golint a try.

> All the tests pass with the current state of my repository. I would
> like to merge your changes into mine so that we are testing the
> same code and can hopefully narrow down the possibilities for the
> failing tests.

> Does this work for you?

> snmpwalk -v 3 -u authPrivUser -l authPriv -A testingpass9876543210 -x
> DES -X testingpass9876543210 gosnmp-test-host .1.3.6.1.2.1.1.1.0

> —
>
Reply to this email directly or view it on GitHub[1].



Links:

  1. https://github.com/soniah/gosnmp/issues/16#issuecomment-73470324

**Comment by soniah** [comment]
No worries, thanks to you for writing the code! I realised I had a
"brain fart" earlier today, by trying to pull in your changes via meld
:-/ I didn't realise you'd forked off me, because github wasn't showing
it on the graph.

Anyway, what I've done is pulled your work into a new branch, rebased
your work against my master, then added on the tweaks from the emails
we've had today. I've called your branch "whit_master_rebase", and
renamed the old branch to zz_whit (I'll keep it around for a few days,
just in case; zz_ is my "trash" prefix). Some of my tweaks are
debatable, so feel free to revert them if you think so. Also I was
pretty fast and loose in my rebase, hence the commit with the message
"fix up rebase".

I've also set you up as a "project collaborator" on soniah/gosnmp, so
you can easily create branches on "whit_master_rebase", if that works
for you (eg for squashing your commits, golint, etc).

Thanks again for all your work, I'm sure we'll get there after a while
:-)

Sonia.




On Mon, Feb 9, 2015, at 19:30, Whitham D. Reeve II wrote:
> I'm signing off for now - It's still Sunday and Monday is just around
> the corner. I really appreciate your efforts Sonia. Sorry for using so
> many commits, maybe I should have rebased before bringing it up. I
> will make the code pass golint in the morning. Then we can let it bake
> for a while. I will test this on a few devices on our network and fix
> problems as they come.

> —
>
Reply to this email directly or view it on GitHub[1].



Links:

  1. https://github.com/soniah/gosnmp/issues/16#issuecomment-73472843

**Comment by soniah** [comment]
I've also broken up my tweaks into tweaks 1-10, hopefully this will make
it easier to fix incorrect ones (from my rebase or from my first use of
meld). We can later squash a lot of these commits.

On Mon, Feb 9, 2015, at 21:14, Sonia Hamilton wrote:
> No worries, thanks to you for writing the code! I realised I had a
> "brain fart" earlier today, by trying to pull in your changes via meld
> :-/ I didn't realise you'd forked off me, because github wasn't
> showing it on the graph.
>
> Anyway, what I've done is pulled your work into a new branch, rebased
> your work against my master, then added on the tweaks from the emails
> we've had today. I've called your branch "whit_master_rebase", and
> renamed the old branch to zz_whit (I'll keep it around for a few days,
> just in case; zz_ is my "trash" prefix). Some of my tweaks are
> debatable, so feel free to revert them if you think so. Also I was
> pretty fast and loose in my rebase, hence the commit with the message
> "fix up rebase".
>
> I've also set you up as a "project collaborator" on soniah/gosnmp, so
> you can easily create branches on "whit_master_rebase", if that works
> for you (eg for squashing your commits, golint, etc).
>
> Thanks again for all your work, I'm sure we'll get there after a
> while :-)
>
> Sonia.
>
>
>
>
> On Mon, Feb 9, 2015, at 19:30, Whitham D. Reeve II wrote:
>> I'm signing off for now - It's still Sunday and Monday is just around
>> the corner. I really appreciate your efforts Sonia. Sorry for using
>> so many commits, maybe I should have rebased before bringing it up. I
>> will make the code pass golint in the morning. Then we can let it
>> bake for a while. I will test this on a few devices on our network
>> and fix problems as they come.

>> —
>>
Reply to this email directly or view it on GitHub[1].



Links:

  1. https://github.com/soniah/gosnmp/issues/16#issuecomment-73472843

**Comment by wdreeveii** [comment]
I found some issues and corrected them, and reorganized the code and added comments for clarity. I linted it and made a thorough review of my changes. The tests pass reliably over here. I want to do some more thorough testing this week and will consider squashing commits when I see how it works in production.

**Comment by soniah** [comment]
Cool, let me know when you're finished :-)

On Tue, Feb 10, 2015, at 19:13, Whitham D. Reeve II wrote:
> I found some issues and corrected them, and reorganized the code and
> added comments for clarity. I linted it and made a thorough review of
> my changes. The tests pass reliably over here. I want to do some more
> thorough testing this week and will consider squashing commits when I
> see how it works in production.

> —
>
Reply to this email directly or view it on GitHub[1].



Links:

  1. https://github.com/soniah/gosnmp/issues/16#issuecomment-73660041

**Comment by wdreeveii** [comment]
This code is now working well in production. I have exhausted my implementations of snmpd to test against. 

It works well on net-snmp snmpd as well as the snmpd on some weird radio gear. Do you guys know of any other snmpds that I should test against?

**Comment by soniah** [comment]
No, getting devices to test against is difficult; that's why at one stage I was using Verax for testing (see the Verax directory for that; the code probably doesn't work at the moment). Also the reason I put packet dumps in the tests - can you do that with SNMPv3 - maybe the encryption will prevent that.

**Comment by wdreeveii** [comment]
I tested the SNMPV3 changes against a variety of devices, and I'm confident that it is ready for production. I also implemented AES encryption as defined in RFC3826. 

I am ready to submit a pull request, but I know Travis-CI will complain about the new tests unless you add something to the effect of below to your init script:

echo "createUser noAuthNoPrivUser" >> /etc/snmp/snmpd.conf
echo "createUser authMD5OnlyUser  MD5 testingpass0123456789" >> /etc/snmp/snmpd.conf
echo "createUser authSHAOnlyUser  SHA testingpass9876543210" >> /etc/snmp/snmpd.conf
echo "createUser authMD5PrivDESUser MD5 testingpass9876543210 DES" >> /etc/snmp/snmpd.conf
echo "createUser authSHAPrivDESUser SHA testingpassabc6543210 DES" >> /etc/snmp/snmpd.conf
echo "createUser authMD5PrivAESUser MD5 AEStestingpass9876543210 AES" >> /etc/snmp/snmpd.conf
echo "createUser authSHAPrivAESUser SHA AEStestingpassabc6543210 AES" >> /etc/snmp/snmpd.conf

echo "rouser   noAuthNoPrivUser noauth" >> /etc/snmp/snmpd.conf
echo "rouser   authMD5OnlyUser auth" >> /etc/snmp/snmpd.conf
echo "rouser   authSHAOnlyUser auth" >> /etc/snmp/snmpd.conf
echo "rouser   authMD5PrivDESUser authPriv" >> /etc/snmp/snmpd.conf
echo "rouser   authSHAPrivDESUser authPriv" >> /etc/snmp/snmpd.conf
echo "rouser   authMD5PrivAESUser authPriv" >> /etc/snmp/snmpd.conf
echo "rouser   authSHAPrivAESUser authPriv" >> /etc/snmp/snmpd.conf

**Comment by soniah** [comment]
Ok Whit thanks! I'll check it out.

On Sun, Mar 1, 2015, at 21:24, Whitham D. Reeve II wrote:
> I tested the SNMPV3 changes against a variety of devices, and I'm
> confident that it is ready for production. I also implemented AES
> encryption as defined in RFC3826.

> I am ready to submit a pull request, but I know Travis-CI will
> complain about the new tests unless you add something to the effect of
> below to your init script:

> echo "createUser noAuthNoPrivUser" >> /etc/snmp/snmpd.conf
>
echo "createUser authMD5OnlyUser MD5 testingpass0123456789" >>
/etc/snmp/snmpd.conf
>
echo "createUser authSHAOnlyUser SHA testingpass9876543210" >>
/etc/snmp/snmpd.conf
>
echo "createUser authMD5PrivDESUser MD5 testingpass9876543210 DES" >>
/etc/snmp/snmpd.conf
>
echo "createUser authSHAPrivDESUser SHA testingpassabc6543210 DES" >>
/etc/snmp/snmpd.conf
>
echo "createUser authMD5PrivAESUser MD5 AEStestingpass9876543210 AES" >>
/etc/snmp/snmpd.conf
>
echo "createUser authSHAPrivAESUser SHA AEStestingpassabc6543210 AES" >>
/etc/snmp/snmpd.conf

> echo "rouser noAuthNoPrivUser noauth" >> /etc/snmp/snmpd.conf
>
echo "rouser authMD5OnlyUser auth" >> /etc/snmp/snmpd.conf
>
echo "rouser authSHAOnlyUser auth" >> /etc/snmp/snmpd.conf
>
echo "rouser authMD5PrivDESUser authPriv" >> /etc/snmp/snmpd.conf
>
echo "rouser authSHAPrivDESUser authPriv" >> /etc/snmp/snmpd.conf
>
echo "rouser authMD5PrivAESUser authPriv" >> /etc/snmp/snmpd.conf
>
echo "rouser authSHAPrivAESUser authPriv" >> /etc/snmp/snmpd.conf

> —
>
Reply to this email directly or view it on GitHub[1].



Links:

  1. https://github.com/soniah/gosnmp/issues/16#issuecomment-76590974

**Comment by codedance** [comment]
Hi Guys,

I have some SNMP v3 devices and would be happy to do some testing.  Are we at a point where we'd find this useful?

**Comment by soniah** [comment]
Probably. I believe the branch is 'whit_master_rebase' in gosnmp/soniah.

On Mon, Mar 2, 2015, at 08:52, Chris Dance wrote:
> Hi Guys,

> I have some SNMP v3 devices and would be happy to do some testing. Are
> we at a point where we'd find this useful?

> —
>
Reply to this email directly or view it on GitHub[1].



Links:

  1. https://github.com/soniah/gosnmp/issues/16#issuecomment-76633198

**Comment by soniah** [comment]
Done.
