### ISSUE TITLE
Issue with timeout and response

### ISSUE THREAD

**Issue by mehdipourfar** [soniah/gosnmp#161]
According to this article, for each request we should wait for the given timeout.
[Timeout and Retries](https://www.webnms.com/snmp/help/snmpapi/snmpv3/v1/timeout.html)
For example if timeout is 10 seconds and retries value is 3, we should wait 30 seconds for an unresponsive device. But gosnmp creates a finalDeadline variable from the timeout and do all the retries within that specific time.

**Comment by soniah** [comment]
Thanks Mehdi for leting me know. I won't be fixing this for the moment.

**Comment by soniah** [comment]
I don't have the time at the moment :-) I used to ask people for PR's, but now I don't ask ;-)
