### ISSUE TITLE
Should /examples work 'out of the box'?

### ISSUE THREAD

**Issue by IkiM0no** [soniah/gosnmp#163]
Hi @soniah we are very keen on using `gosnmp` to implement a trap receiver.

I wanted to do some groundwork with the library to test before we dive into dev, and am trying to get /examples/trapserver.go and /examples/trapsend_v2plus.go to work together, but trapsend keeps complaining:
`write: connection refused`
and server never logs a trap received.

Should these work together 'out of the box'?

It would be great if we could get some boiler plate examples working to illustrate a 'client' (in our case it will be a wireless lan controller), and server (trap receiver) using the library.

Please let me know if I can provide any additional clarity. Thanks!

**Comment by soniah** [comment]
Closing, as I don't have time to fix this.
