### ISSUE TITLE
why negotiateInitalSecurityParameters use local snmpv3 SecurityParameters?

### ISSUE THREAD

**Issue by wanrui** [soniah/gosnmp#171]
https://github.com/soniah/gosnmp/blob/cd9a07ae5a52ff5851e1cfed624e5415b6e9a6ee/v3.go#L88

 soniah/gosnmp  need negotiateInitalSecurityParameters, then on soniah/gosnmp use fuc isAuthentic
result is receive packet, his Flag is not our config file msgFlag 
why   decided to decode SecurityParameters with no testauthentic when result flag is noauthnopri but x flag is authpri ?

**Comment by soniah** [comment]
Hi Wan,

It's probably a bug :-0 I've just made a small fix to isAuthentic(), perhaps you could write a PR? :-)

**Comment by soniah** [comment]
Sorry Wan this change was rejected by @wdreeveii in #172

My mistake, I didn't notice the whole conversation.

**Comment by wanrui** [comment]
How did you   fix to isAuthentic?:-)
