### ISSUE TITLE
Setting IPAddress marshalling present but not used

### ISSUE THREAD

**Issue by MrSpock** [soniah/gosnmp#179]
Hi,
Some time ago you've merge my pull request for some SNMP Sets.
Code for marshalling to set IPAddress type is present in source code (marshal.go:658), but it's not used because gosnmp.go:364 is missing proper switch option.
Please find attached single-line patch that makes making snmpset with ipaddress oid possible and pcap file that confirms its works.

[ipaddress-patch.txt](https://github.com/soniah/gosnmp/files/2821214/ipaddress-patch.txt)

[ipaddress-snmpset.pcapng.gz](https://github.com/soniah/gosnmp/files/2821221/ipaddress-snmpset.pcapng.gz)

**Comment by soniah** [comment]
Thanks Marcin, I've added your changes 👍
