### ISSUE TITLE
SNMPv1 Trap Specific trapID should not be cast to byte value

### ISSUE THREAD

**Issue by chbuescher** [soniah/gosnmp#182]
When sending a SNMPv1 Trap, the Specific Trap ID - which is an int32 - is cast to a byte value.
Therefore legal IDs greater 128 are modified, for example instead of sending a specific id 4648 an id of 40 will be send. Instead of casting to byte you should use marshalInt32(packet.SpecificTrap).
The same is true for the generic trap id, but i don't know of anybody using generic trap ids bigger than 6, so casting to byte is probably ok.

**Comment by soniah** [comment]
Hi, I've just fixed that, have a look at the recent commits. Let me know how you go :-)

**Comment by chbuescher** [comment]
Hallo,

yes, i've tested the commits. The test looks good !

Thanks
Christoph

Fiducia & GAD IT AG | www.fiduciagad.de
AG Frankfurt a. M. HRB 102381 | Sitz der Gesellschaft: Frankfurt a. M. |
USt-IdNr. DE 143582320
Vorstand: Klaus-Peter Bruns (Vorsitzender), Jens-Olaf Bartels,
Martin Beyer, Birgit Frohnhoff, Carsten Pfläging, Jörg Staff
Vorsitzender des Aufsichtsrats: Jürgen Brinkmann



Von:	Sonia Hamilton <notifications@github.com>
An:	soniah/gosnmp <gosnmp@noreply.github.com>
Kopie:	chbuescher <Christoph.Buescher@fiduciagad.de>, Author
            <author@noreply.github.com>
Datum:	27.03.2019 09:27
Betreff:	Re: [soniah/gosnmp] SNMPv1 Trap Specific trapID should not be
            cast to byte value (#182)



Hi, I've just fixed that, have a look at the recent commits. Let me know
how you go :-)
