### ISSUE TITLE
when gosnmptrap v3 server,  use snmptrap  to send msg ,but  auth fail

### ISSUE THREAD

**Issue by cabbage812** [soniah/gosnmp#183]
code 
```

package main

import (
	"log"
	"net"
	"os"
	"time"

	g "github.com/soniah/gosnmp"
)

func main() {
	tl := g.NewTrapListener()
	tl.OnNewTrap = func(packet *g.SnmpPacket, addr *net.UDPAddr) { log.Println(addr.IP) }
	tl.Params = &g.GoSNMP{
		Version:       g.Version3,
		Timeout:       time.Duration(2) * time.Second,
		MaxOids:       g.MaxOids,
		Logger:        log.New(os.Stdout, "SNMP ", 0),
		MsgFlags:      g.AuthPriv,
		SecurityModel: g.UserSecurityModel,
		SecurityParameters: &g.UsmSecurityParameters{
			UserName:                 "user",
			AuthenticationProtocol:   g.MD5,
			AuthenticationPassphrase: "password",
			PrivacyProtocol:          g.DES,
			PrivacyPassphrase:        "password",
			Logger:                   log.New(os.Stdout, "SECURITY ", 0),
		},
	}

	if err := tl.Listen("0.0.0.0:9162"); err != nil {
		log.Fatalf("error in listen: %s", err)
	}
}
```
net-snmp 

> snmptrap -v 3 -l authPriv -a MD5 -A password -x DES -X password -u user 127.0.0.1:9162  "" 1.3.6.1.4.1.2345

with engineID is the same 

> snmptrap -v 3 -e 0x8000000004736e6d70676f -l authPriv -a MD5 -A password -x DES -X password -u user 127.0.0.1:9162  "" 1.3.6.1.4.1.2345

log 

> SNMP Packet sanity verified, we got all the bytes (166)
> SNMP Parsed version 3
> SNMP Parsed message ID 1087451304
> SNMP Parsed message max size 65507
> SNMP parsed msg flags 03
> SNMP Parsed security model 3
> SNMP Parsed authoritativeEngineID 80001F8880786C2A3DEE2F925C00000000
> SNMP Parsed authoritativeEngineBoots 13
> SNMP Parsed authoritativeEngineTime 0
> SNMP Parsed userName user
> SNMP Parsed authenticationParameters 2a766e01fae758aa21de4f44
> SNMP Parsed privacyParameters 0000000D2AFB998E
> SNMP UnmarshalTrap v3 auth: Incoming packet is not authentic, discarding

**Comment by cabbage812** [comment]
v3_usm.go #414 
modify `copy(extkey[:], sp.secretKey)` to `copy(extkey[:], packetSecParams.secretKey)` can fix it

**Comment by soniah** [comment]
Thanks, I've merged this into dev branch.
