### ISSUE TITLE
why is SNMPError an uint8, not uint32

### ISSUE THREAD

**Issue by smthemofbl** [soniah/gosnmp#184]
https://github.com/soniah/gosnmp/blob/b91861a46ef9107f5311ae2ba6dce924cc75b318/gosnmp.go#L174

the following image is snmpv1 response format
![image](https://user-images.githubusercontent.com/44920203/55058522-2d394800-50a7-11e9-923e-5eaf4d9e7edf.png)
ref:http://www.tcpipguide.com/free/t_SNMPVersion1SNMPv1MessageFormat-2.htm

![image](https://user-images.githubusercontent.com/44920203/55059660-7a6ae900-50aa-11e9-9059-9606b6b0654a.png)

**Comment by soniah** [comment]
Because the underlying type of the rawError is int.

https://blog.golang.org/laws-of-reflection
