### ISSUE TITLE
Tagging format is inconsistent with Golang tools

### ISSUE THREAD

**Issue by siggimoo** [soniah/gosnmp#186]
Golang version-aware tools such as `vgo` and the upcoming Golang modules system only support tags with the format `vN.N.N`. All others are ignored. As none of the tags in this repo follow the convention, tools are falling back to their last-resort behavior which is to form dependencies on specific commits (e.g. `v0.0.0-20190220004421-68e8beac0db9`).

Recommend that tags be modified to follow the tooling convention (e.g. `v1.18` --> `v1.18.0`).

**Comment by soniah** [comment]
This Milo for submitting the bug 👍  I've cleaned up the tags.
