### ISSUE TITLE
Implement RFC7860 HMAC-SHA-2 hash functions

### ISSUE THREAD

**Issue by benschweizer** [soniah/gosnmp#188]
Newer hash functions were standardised for SNMPv3 USM in RFC7860, theye are implemented at newer network equipment and it would be great to support them.

**Comment by soniah** [comment]
Thanks Benjamin.

**Comment by wdreeveii** [comment]
Created branch sha2 (https://github.com/soniah/gosnmp/compare/master...soniah:sha2) to track these changes.

**Comment by wdreeveii** [comment]
I tried to implement some unit tests for this functionality - but not having much luck.

I do not believe the net-snmp daemon shipping with my distro supports these extensions - I am not seeing any errors logged to the console, but then again, my manual tests with snmpwalk aren't working.

$ snmpwalk -v3 -u authSHA224OnlyUser -a SHA224 -A testingpass5123456 -l authNoPriv 127.0.0.1
Invalid authentication protocol specified after -a flag: SHA224

Do you know if I am running into a version issue? Or perhaps net-snmp doesn't support RFC7860?

**Comment by wdreeveii** [comment]
@cxcv do you have equipment available to test this? Can you give this branch a whirl and separately collect some packet dumps so I can create unit tests instead.

**Comment by kido5217** [comment]
@wdreeveii what version of net-snmp do you use? You need 5.8 for RFC 7860 support.

**Comment by wdreeveii** [comment]
@kido5217, I am running 5.7.3. I was able to build 5.8 and will be testing with it shortly, thanks!

**Comment by cxcv** [comment]
We’ve artista switches where I can test, but I’m out of office this week, will report afterwards

**Comment by soniah** [comment]
Great, thanks Benjamin ⚡️

**Comment by hauti123** [comment]
May I ask what the plans are for completing this feature?

**Comment by wdreeveii** [comment]
@hauti123, are you able to test the branch and let me know if its working for you?

**Comment by hauti123** [comment]
I will check if we have some devices around I could use. 
Meanwhile, do you know
http://snmplabs.com/snmpsim/index.html ?

**Comment by hauti123** [comment]
Unfortunately, I was not able to find a device that supports RFC7860 yet, so I gave this a shot with the SNMP Sim mentioned in my last post:

SHA256 and SHA224 worked fine, SHA384 and SHA512 failed with an authentication error.
This should be reproducible fairly easy with the sim. Some pitfalls I stumbled over:

* pip install wasn't enough on my Windows machine, I had to check out the repo and do a 
'python setup.py install'

* I made a clean ./data directory and placed a copy of 'public.snmprec' from the sim repo there

* in the test you have to set 'Default.ContextName="public"', otherwise the sim won't answer

I've attached a file with the commands I used to start the sim:
[simcmds.txt](https://github.com/soniah/gosnmp/files/4415755/simcmds.txt)

Let me know if I can provide additional help. Should I get hold of a suitable device, I'll let you know.

**Comment by hauti123** [comment]
I just discovered that there is actually a public demo SNMP service that can be used for that kind of tests:
http://snmplabs.com/snmp-simulation-service.html

**Comment by hauti123** [comment]
For SHA512 the sim answers with a REPORT that contains SNMP-USER-BASED-SM-MIB::usmStatsWrongDigests, but no error status. Still, this could give a hint that a wrong digest has been used. If tested the same request with net-snmp, it worked fine, so, for now, I would rule out a sim malfunction.

**Comment by hauti123** [comment]
I did some digging in the code and comparing with pysnmp to see where the difference in calculation of the digest is. The reason why the digest is calculated wrong is that the length of the used keys shall be the same as the block size of the used hash algorithm. If the secret key is too short, it needs to be padded with 0, if it's to long it needs to be hashed (see RFC2104).
But: there's no need to do this in gosnmp, it's already implemented in crypto/hmac.

I've tested this using demo.snmplabs.com and it worked perfectly for all hash functions (MD5 -SHA512).

**Comment by soniah** [comment]
That would be great @hauti123, thanks for all your effort on this 🥇 😄 

Would you mind submitting a PR?

**Comment by hauti123** [comment]
I would love to, I already tried to push my own branch, but i didnt have
the permissions.

Sonia Hamilton <notifications@github.com> schrieb am So., 5. Apr. 2020,
00:20:

**Comment by soniah** [comment]
Yes git/github can be a git confusing. You need to fork the repo to your account, push to your account, then send a PR from your account. I use [hub](https://github.com/github/hub) for this, but it might make your life more difficult than easier if you're not used to it 😮

**Comment by StefanHauth** [comment]
Thx, I will provide my PR in the next days.

**Comment by soniah** [comment]
Cleaning up all old issues. If this is still a problem, please reopen issue.
