### ISSUE TITLE
data race with BulkWalk

### ISSUE THREAD

**Issue by ps0296** [soniah/gosnmp#189]
When I use BulkWalk, go detects a data race.

```
err = snmpSocket.BulkWalk("1.3.6.1.2.1.2.2.1.3", func(pdu gosnmp.SnmpPDU) error {
  return nil
})
```

**Comment by ps0296** [comment]
nvm this was a bug on my end, reusing err variable

**Comment by soniah** [comment]
Thanks anyway for reporting it, any feedback helps :-)
