### ISSUE TITLE
when scanning millions of devices, timeout rates increase but cpu is low

### ISSUE THREAD

**Issue by ps0296** [soniah/gosnmp#191]
We are using GOSNMP to get data for millions of devices. We have noticed as we scan more and more devices, timeouts start increasing but CPU and memory stays low.
With a 4 vCPU and 16G VM, we can do around 1500 devices per second per VM, trying to get higher throughput but then timeout errors occur more often.

Any recommendations on ways to effectively use this lib when dealing with this kind of load?

Current optimizations on our end:
- setting linux file descriptors to couple hundred thousand, never reach this limit
- We use sync pool to re-use instances of GoSNMP
- keeping re-try to 1 with 6 second timeout, higher retries causes requests to take longer
- leveraging getbulk and bulkwalk as much as possible

Trying to figure out what might be the bottleneck if it's not CPU, memory or network bandwidth.

**Comment by soniah** [comment]
Hi CodeNight, I don't have any easy solutions. But what I've done is setup a wiki for this, I'm starting to get more questions like this, as GoSNMP adoption spreads.

https://github.com/soniah/gosnmp/wiki

Thanks again, Sonia.

**Comment by ps0296** [comment]
Is there a way to re-use sockets instead of opening and closing for each device?

**Comment by soniah** [comment]
There possibly is; pull requests are welcome.

**Comment by int3rlop3r** [comment]
Found this interesting comment. Not sure if it's the same issue.

https://github.com/microsoft/ethr/blob/master/ethr.go#L206

**Comment by soniah** [comment]
Thanks @int3rlop3r  I've updated the wiki

**Comment by abarrios1** [comment]
I am starting to run into the same issue polling millions of devices as well. I have tried setting `runtime.GOMAXPROCS(1024)` and still running into the same issue. @ps0296 by chance did you find a solution that helped you out?

**Comment by ps0296** [comment]
So the bottleneck on our end came from AWS itself. If you use AWS security groups, try keeping traffic open for all, and testing performance. For us this was a huge bottleneck.

Other things we implemented:
re-use objects as much as possible with Pool
