### ISSUE TITLE
Remove testing dependencies from gosnmp package

### ISSUE THREAD

**Issue by skyfmmf** [soniah/gosnmp#198]
I made a pull request at influxdata/telegraf#5870 to integrate the new TCP capabilities into telegraf. During the code review there was the question if it was possible to move the generated mocks of gosnmp from the gosnmp package into another one. This would remove the transitive dependency on gomock from projects depending on gosnmp.

I think it is a good idea to try not to have testing dependencies in the gosnmp package. In case of the mocks I am not sure where they are used and therefore not sure about the implications that would arise when moving them into another repository. Maybe @IvanRadakovic (who generated the mocks) can help with this?

It may also be a good ides to remove the dependency on "github.com/stretchr/testify/assert" from the gosnmp package but I think this may also need some discussion. The tested functions could be made public to allow the tests to be moved into another package or the tests could be written without the assert package. 

I have created this issue for the discussion, when there is a consensus I am happy to implement it.

**Comment by IvanRadakovic** [comment]
The motivation behind this was for when people use this library they will write tests for their code, and to do so without having to hit a live machine, they would need mocks. So instead of requiring each person to generate their own mocks, it would be more convenient to have the mocks included.

I do agree that it would be a good idea to not have transitive dependencies on gomock. The only implication of moving them into another repository is that it would affect all the people that are currently using the mocks.

**Comment by skyfmmf** [comment]
Do you have an example for an code base that uses the mocks? How much effort would be needed when moving the mocks to a different package? In my naive opinion it would only be necessary to add/modify one import.

I think @soniah has to decide how to perform such changes that may break existing code bases.

**Comment by skyfmmf** [comment]
Is there a way we can get progress with this issue? I would like to use new features of gosnmp in telegraf, but the transitive dependency on gomock prevents the merge of my pull request. 

I think it is acceptable to request small changes to their tests (updating the imports) from the users of the library, if they use the mocks at all, when they upgrade to a newer version. In my opinion their production code would not be affected by the PR I opened. 

On the other hand gosnmp gets a cleaner project project structure and gets more lightweight when included in another project.

**Comment by IvanRadakovic** [comment]
I am no longer part of that team so I cannot find an example of the codebase anymore. As for your reasoning, I completely agree and support your decision to make those changes!

**Comment by soniah** [comment]
TODO: https://github.com/benbjohnson/testing

**Comment by soniah** [comment]
Cleaning up all old issues. If this is still a problem, please reopen issue.
