### ISSUE TITLE
logger shows up in cpu profile

### ISSUE THREAD

**Issue by ps0296** [soniah/gosnmp#200]
I added the cpu profile image. I declare SNMP setting logger to nil but still I see logger consuming quite a bit of CPU, any clue what might be going on?

```
			snmpSocket := &gosnmp.GoSNMP{
				Port:               161,
				Community:          "",
				Version:            gosnmp.Version2c,
				ExponentialTimeout: true,
				Logger:         nil,
				MaxOids:        10,
				MaxRepetitions: 10,
			}
```

![image](https://user-images.githubusercontent.com/4612372/62268018-62122e80-b3fc-11e9-9fee-9d66d31fe3a9.png)

**Comment by soniah** [comment]
Cleaning up all old issues. If this is still a problem, please reopen issue.
