### ISSUE TITLE
strange timeout when walking LLDP oid using snmp_exporter

### ISSUE THREAD

**Issue by visualcjy** [soniah/gosnmp#205]
when walking som Huawei switch's OID 1.0.8802.1.1.2.1.4.1.1.9，it will timeout. but the others is correct.
DEBU[0020] Walking target "192.168.52.240" subtree "1.0.8802.1.1.2.1.4.1.1.7" source="collector.go:156"
DEBU[0020] Walk of target "192.168.52.240" subtree "1.0.8802.1.1.2.1.4.1.1.7" completed in 210.145534ms source="collector.go:166"
DEBU[0020] Walking target "192.168.52.240" subtree "1.0.8802.1.1.2.1.4.1.1.9" source="collector.go:156"
INFO[0080] Error scraping target 192.168.52.240: error walking target 192.168.52.240: Request timeout (after 3 retries) source="collector.go:211"
DEBU[0080] Scrape of target '192.168.52.240' with module 'lldp' took 60.457660 seconds source="main.go:98"

but if i snmpwalk , it's OK.
snmpwalk -v3 -l authpriv -u ops -a sha -A "abc" -x aes -X "abc" 192.168.52.240 1.0.8802.1.1.2.1.4.1.1.9
iso.0.8802.1.1.2.1.4.1.1.9.253088189.43.1 = STRING: "CU_S5720_DW"
iso.0.8802.1.1.2.1.4.1.1.9.253088189.47.1 = STRING: "CU_USG6600_M"
iso.0.8802.1.1.2.1.4.1.1.9.253088189.52.1 = STRING: "CU_CE6855_C"

is the 253088189 oid is too big to timeout ?

**Comment by shdxiang** [comment]
I meet a similar problem, `snmp_exporter` timeout frequently, but `snmpget` never.
https://github.com/prometheus/snmp_exporter/issues/487

**Comment by soniah** [comment]
Hmmm I don't know where to start with this one... @shdxiang you're in a better position to debug this if you can reliably reproduce the problem.

**Comment by shdxiang** [comment]
I have tested a Python version: https://github.com/etingof/pysnmp/. It also did not timeout.

**Comment by soniah** [comment]
Cleaning up all old issues. If this is still a problem, please reopen issue.
