### ISSUE TITLE
Set function fails if value is an Integer 128

### ISSUE THREAD

**Issue by froimartin** [soniah/gosnmp#210]
Hi,

I'm using the Set function with a Integer of 128, but the agent receives a -128.

As @ffcactus mentioned in https://github.com/soniah/gosnmp/issues/204#issue-485632244, a value over 127 must be encoded using two bytes, and the value 128 is currently encoded using one byte.

I think the problem is located in the file **helper.go** in the function **marshalInt32**
https://github.com/soniah/gosnmp/blob/e1cc1327e769b769aae65cf375db306992218b59/helper.go#L279-L292

I suspect the <= in the lines 283, 286 and 289 should be replaced by <

**Comment by soniah** [comment]
Thanks @wdreeveii :-)
