### ISSUE TITLE
How parsing a mib file and generate a tree-view in memory

### ISSUE THREAD

**Issue by yboujraf** [soniah/gosnmp#211]
Dear,

Is it planned to support the import of a mib file and generate in memory the tree structure ?

Best Regards,
Youssef

**Comment by danielnelson** [comment]
I've no experience with it myself, but you could try this project: https://github.com/sleepinggenius2/gosmi

**Comment by soniah** [comment]
Hi @yboujraf, I don't have any plans for a mib parser. As @danielnelson suggested, have a look at https://github.com/sleepinggenius2/gosmi.
