### ISSUE TITLE
Building an snmp agent with mib file

### ISSUE THREAD

**Issue by yboujraf** [soniah/gosnmp#212]
Dear,

I have my own apps and I need to share some metrics through snmp.
Is it planned to support an snmp agent?

Best Regards,
Youssef

**Comment by yboujraf** [comment]
Dear @soniah , I googled too many time to find go snmp agent and/or mib parser but nothhing.

Maybe you have some good link

Best Regards,
Youssef

**Comment by soniah** [comment]
Hi @yboujraf. The file `examples/trapserver.go` may help you. I can't recommend a mib parser.. Thanks for your enquiry.

**Comment by pjfernan** [comment]
Hello Youssef. I am looking for same example or packet. Have you found something useful for your project?
