### ISSUE TITLE
doc: wrong description for private field GoSNMP.loggingEnabled, logic reversed

### ISSUE THREAD

**Issue by gaissmai** [soniah/gosnmp#213]
Hi,
stumbled upon this IMHO wrong description:

`// loggingEnabled is set if the Logger is nil, short circuits any 'Logger' calls
loggingEnabled bool`

should be

`// loggingEnabled is set if the Logger isn't nil, otherwise short circuits any 'Logger'
loggingEnabled bool`
	
Regards and thanks for go-snmp!

  Charly

**Comment by soniah** [comment]
Fixed, thanks!
