### ISSUE TITLE
Raw variable data?

### ISSUE THREAD

**Issue by ShyLionTjmn** [soniah/gosnmp#214]
Would be nice having `Variable.Raw []byte` field
When i want to have IPAddress as `uint` instead of `string`, for example, and such

**Comment by soniah** [comment]
Sounds like a good idea. Would you mind trying to write a PR?

The functions `sendOneRequest` and `send` are probably good places to start.

Very sorry about the delay in getting back to you 👎

**Comment by soniah** [comment]
Cleaning up all old issues. If this is still a problem, please reopen issue.
