### ISSUE TITLE
Context.Err() not returned when context expires during last retry

### ISSUE THREAD

**Issue by geofduf** [soniah/gosnmp#234]
When the context expires or is canceled during the last retry, a standard timeout error is returned instead of the context error.

https://github.com/soniah/gosnmp/blob/19a3e6384e3e70978a991e11ebdbcaee08ff91f4/marshal.go#L140-L151

Adding a check of `x.Context.Err()` inside the `if retries > x.Retries {}` block (line 140) to set `err` accordingly may help.

**Comment by soniah** [comment]
Thanks. Does this refer to the work that Stefan is doing and [the problems we're having on that PR](https://github.com/soniah/gosnmp/pull/231), or just in general?

**Comment by geofduf** [comment]
In general. I think it is only a problem when the context has a deadline.  Here is a simple way to reproduce the issue:

```go
func main() {
	start := time.Now()
	defer func() {
		fmt.Printf("elapsed: %s\n", time.Since(start))
	}()

	ctx, cancel := context.WithTimeout(context.Background(), 2*time.Second)
	defer cancel()

	snmp := gosnmp.GoSNMP{
		Target:    "127.0.0.1",
		Port:      161,
		Community: "noResponseExpected",
		Version:   gosnmp.Version2c,
		Retries:   0,
		Timeout:   5 * time.Second,
		Context:   ctx,
	}
	if err := snmp.Connect(); err != nil {
		fmt.Println(err)
		return
	}
	defer snmp.Conn.Close()

	if _, err := snmp.BulkWalkAll("1.3.6.1.2.1.2.2"); err != nil {
		fmt.Println(err)
		return
	}

	fmt.Println("success...")
}
```
Result :
```text
Request timeout (after 0 retries)
elapsed: 2.0004886s
```
Expected:
```text
context deadline exceeded
elapsed: 2.0004886s
```

https://github.com/soniah/gosnmp/blob/19a3e6384e3e70978a991e11ebdbcaee08ff91f4/marshal.go#L153-L156

Here, the connection deadline is set to `x.Context` existing deadline, which is the expected behavior. But in the next iteration `retries > x.Retries` (line 140) breaks the loop with a standard timeout error. Which does not seem accurate in our case as the timeout is actually related to the context.

**Comment by geofduf** [comment]
This could probably be fixed by identifying / keeping track of the connection deadline source (configured timeout or context) and setting the error accordingly if a timeout is detected. I created a fix234 branch to illustrate this approach.

**Comment by soniah** [comment]
Thanks, I've merged this.

**Comment by geofduf** [comment]
Thanks !

For the record :

Breaks the “retries” loop to prevent unnecessary iterations : with original code, the context sometimes does not return an error yet when it is evaluated for cancellation / expiration (```if x.Context.Err() != nil {...}``` block) right after a context based timeout.

Returns a ```context.DeadlineExceeded``` error to facilitate error handling, be actually based on the assumption that the context has expired / is about to expire. It should be replaced by a dedicated error if it is seen as a problem in the future.

Can I close the issue ?

**Comment by soniah** [comment]
Thanks @geofduf 🍰  , I've merged this
