### ISSUE TITLE
race issues with global logging vars

### ISSUE THREAD

**Issue by sam3000** [soniah/gosnmp#28]
Hi,

Global vars LoggingDisabled bool and slog Logger are detected as not being safe owing to unsynchronized reads/writes (when calling gosnmp from concurrent go routines).   Visible using go run -race.

I guess there are two directions:
1) created synchronized access methods to global logging state
2) remove global vars and pass state around from gosnmp.GoSNMP

Thoughts ?

**Comment by rjammala** [comment]
Hi

Any updates on this one? Will this have any real impact on the code (i.e. can cause it to panic/crash?). Please let me know.

**Comment by rjammala** [comment]
I sent this pull request: https://github.com/soniah/gosnmp/pull/59

Can someone please review?

**Comment by soniah** [comment]
merged and tidied.
