### ISSUE TITLE
Optimize Performance

### ISSUE THREAD

**Issue by virtuallynathan** [soniah/gosnmp#3]
Lets eek out as much performance as possible... 
![cpu_profile](https://cloud.githubusercontent.com/assets/3472173/3352886/583ca018-fa64-11e3-8c1f-e06de6248268.png)
![mem_profile](https://cloud.githubusercontent.com/assets/3472173/3352887/584db362-fa64-11e3-8d98-7cac963a4ba0.png)

Here are profiles with tons of samples (ignore the CSV stuff...)

**Comment by soniah** [comment]
Old; closing.
