### ISSUE TITLE
SystemDate is displayed with special characters

### ISSUE THREAD

**Issue by rjammala** [soniah/gosnmp#58]
When I try to get and display the system date using oid: 1.3.6.1.2.1.25.1.2.0, it is displayed with special characters (please see the attachment).

I am using the tip version of go.

$ go version
go version devel +e05b48e Thu Dec 10 08:04:07 2015 +0000 linux/amd64

When I get it through snmpget, I get the normal date:

HOST-RESOURCES-MIB::hrSystemDate.0 = STRING: 2015-12-10,21:39:49.0,+0:0

![screen shot 2015-12-10 at 4 56 28 pm](https://cloud.githubusercontent.com/assets/4990663/11729766/03a20d80-9f5f-11e5-86f5-85893ccadb26.png)

**Comment by rjammala** [comment]
I used the following as an example (I changed the oids):

https://github.com/soniah/gosnmp/blob/master/examples/example3.go

**Comment by wdreeveii** [comment]
The hrSystemDate is not an ascii formatted date.

You will need to convert the octetstring sequence to the desired format.
Here is a description of the contents of the octetstring.

https://www.webnms.com/snmp/help/snmpapi/snmpv3/using_mibs_in_applns/tcs_dateandtime.html



On Thu, Dec 10, 2015 at 12:59 PM, Rajanikanth Jammalamadaka <
notifications@github.com> wrote:

> I used the following as an example (I changed the oids):
>
> https://github.com/soniah/gosnmp/blob/master/examples/example3.go
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/soniah/gosnmp/issues/58#issuecomment-163761530>.
>



-- 
Whitham D. Reeve II
907-764-5263

**Comment by rjammala** [comment]
Thanks @wdreeveii , closing this issue.
