### ISSUE TITLE
gosnmp/helper.go - Request ID failing on what I believe are valid Request IDs

### ISSUE THREAD

**Issue by godsey** [soniah/gosnmp#60]
I'm not sure if this is a correct fix, but it allows my tool to decode these OctetStrings correctly.

I made the slight adjustment to line 484 replacing with 485. I realize the int64 can wrap to an incorrect value via the return int(), but I haven't noticed any unexpected side effects yet.

Failed requests:

parseRawField: request id
0	02 05 00 b4 8b 01 5c 02
8	01 00 02 01 00 30 76 30
parseRawField: request idDebug Type Integer: 2 - 2 - length: 7
[.1.3.6.1.2.1.1.1.0] %!q(*gosnmp.SnmpPacket=<nil>) err: Unable to decode packet: Error in unmarshalResponse: Error parsing SNMP packet request ID: Unable to parse raw INTEGER: 020500b48b015c0201000201003076307406082b06010201010100046848575f5245563a203030324a2c2056454e444f523a20436f6d6d53636f70652c20424f4f54523a20323030392e30312d35382c2053575f5245563a2076322e362e31322e332c204d4f44454c3a204c78532d31363031362c204150505f5245563a20322e362e3138 err: integer too large

09:35:24.419003 IP (tos 0x0, ttl  50, id 0, offset 0, flags [DF], proto: UDP (17), length: 178) x.x.135.154.snmp > x.x.13.141.60483: [udp sum ok]  { SNMPv2c { GetResponse(133) R=-1675185393  .1.3.6.1.2.1.1.1.0="HW_REV: 002J, VENDOR: CommScope, BOOTR: 2009.01-58, SW_REV: v2.6.12.3, MODEL: LxS-16016, APP_REV: 2.6.18" } }
....C..D.0.......public.......&........0v0t..+........hHW_REV: 002J, VENDOR: CommScope, BOOTR: 2009.01-58, SW_REV: v2.6.12.3, MODEL: LxS-16016, APP_REV: 2.6.18

Working:

parseRawField: request id
0	02 04 7a 2f 72 0e 02 01
8	00 02 01 00 30 76 30 74
parseRawField: request idDebug Type Integer NIL: 2 - 2 - length: 6
[.1.3.6.1.2.1.1.1.0] HW_REV: 002J, VENDOR: CommScope, BOOTR: 2009.01-58, SW_REV: v2.6.12.3, MODEL: LxS-16016, APP_REV: 2.6.18

09:35:29.843499 IP (tos 0x0, ttl  50, id 0, offset 0, flags [DF], proto: UDP (17), length: 177) x.x.135.154.snmp > x.x.13.141.38767: [udp sum ok]  { SNMPv2c { GetResponse(132) R=977264967  .1.3.6.1.2.1.1.1.0="HW_REV: 002J, VENDOR: CommScope, BOOTR: 2009.01-58, SW_REV: v2.6.12.3, MODEL: LxS-16016, APP_REV: 2.6.18" } }
....o....0.......public.....:?.G......0v0t..+........hHW_REV: 002J, VENDOR: CommScope, BOOTR: 2009.01-58, SW_REV: v2.6.12.3, MODEL: LxS-16016, APP_REV: 2.6.18

gosnmp/helper.go

477 // parseInt treats the given bytes as a big-endian, signed integer and returns
478 // the result.
479 func parseInt(bytes []byte) (int, error) {
480         ret64, err := parseInt64(bytes)
481         if err != nil {
482                 return 0, err
483         }
484         // if ret64 != int64(int(ret64)) {
485         if ret64 != int64(ret64) {
486                 return 0, errors.New("integer too large")
487         }
488         return int(ret64), nil
489 }

**Comment by soniah** [comment]
Closing. Problem and solution are too difficult to understand, as currently submitted.
