### ISSUE TITLE
snmp.Get(m.snmpOids[i:end]) randomly crashes

### ISSUE THREAD

**Issue by toni-moreno** [soniah/gosnmp#62]
Hi @soniah .

I'm having something strange in my gosnmp client with influxsnmp tool (https://github.com/toni-moreno/influxsnmp/blob/first_big_refactor) 

when running a Cisco Switch scan with the influxsnmp  tool ( cisco has aprox 500 ports) , this is the expected output:

```
#./influxsnmp -showConfig  

...
(a lot of debug loging)
...
...
SNMP host: CISCO_SWITCH_XXXX
=========================================
Host: A.B.C.D Port: 161 Version: 2c
----------------------------------------------
 Measuremet : cisco_cpu
 ----------------------------------------------
        *Metric[Cisco_CPU]      Name[usage]     OID:.1.3.6.1.4.1.9.9.109.1.1.1.1.8.1    (GAUGE)
 Measuremet : cisco_mem
 ----------------------------------------------
        *Metric[Cisco_memFree]  Name[free]      OID:.1.3.6.1.4.1.9.9.48.1.1.1.6.1       (GAUGE)
        *Metric[Cisco_memUsed]  Name[used]      OID:.1.3.6.1.4.1.9.9.48.1.1.1.5.1       (GAUGE)
 Measuremet : cisco_ports
 ----------------------------------------------
        *Metric[ifHCInOctets]   Name[In.bytes]  OID:.1.3.6.1.2.1.31.1.1.1.6     (COUNTER64)
        *Metric[ifHCOutOctets]  Name[Out.bytes] OID:.1.3.6.1.2.1.31.1.1.1.10    (COUNTER64)
        *Metric[ifHCInUcastPkts]        Name[In.packets]        OID:.1.3.6.1.2.1.31.1.1.1.7     (COUNTER64)
        *Metric[ifHCOutUcastPkts]       Name[Out.packets]       OID:.1.3.6.1.2.1.31.1.1.1.7     (COUNTER64)
 ---------------------------------------------------------
                Index[104 / Fa9/6]
                Index[194 / VLAN-434]
                Index[505 / VLAN-251]
                Index[85 / Gi2/37]
                Index[88 / Gi2/40]
  ...
...
...
(+500 ports)
...
...
                Index[220 / VLAN-529]
                Index[46 / Gi1/46]
                Index[55 / Gi2/7]

```

It always crashes when gosnmp.Logger is not set. and randomly ( sometimes yes and sometimes no) when gosnmp.Logger is set.

this is the output.

```
2016/04/11 17:44:04 OK measurement  cisco_ports SNMP RESULT OID .1.3.6.1.2.1.31.1.1.1.7.484 MetricFound 50889
2016/04/11 17:44:04 Rawdata: +0x41b4b0
2016/04/11 17:44:04 DEBUG GET SNMP DATA FROM 1860 to 1920
2016/04/11 17:44:04 selected OIDS [.1.3.6.1.2.1.31.1.1.1.10.376 .1.3.6.1.2.1.31.1.1.1.7.376 .1.3.6.1.2.1.31.1.1.1.7.376 .1.3.6.1.2.1.31.1.1.1.6.376 .1.3.6.1.2.1.31.1.1.1.7.113 .1.3.6.1.2.1.31.1.1.1.7.113 .1.3.6.1.2.1.31.1.1.1.6.113 .1.3.6.1.2.1.31.1.1.1.10.113 .1.3.6.1.2.1.31.1.1.1.7.59 .1.3.6.1.2.1.31.1.1.1.6.59 .1.3.6.1.2.1.31.1.1.1.10.59 .1.3.6.1.2.1.31.1.1.1.7.59 .1.3.6.1.2.1.31.1.1.1.6.146 .1.3.6.1.2.1.31.1.1.1.10.146 .1.3.6.1.2.1.31.1.1.1.7.146 .1.3.6.1.2.1.31.1.1.1.7.146 .1.3.6.1.2.1.31.1.1.1.6.507 .1.3.6.1.2.1.31.1.1.1.10.507 .1.3.6.1.2.1.31.1.1.1.7.507 .1.3.6.1.2.1.31.1.1.1.7.507 .1.3.6.1.2.1.31.1.1.1.6.187 .1.3.6.1.2.1.31.1.1.1.10.187 .1.3.6.1.2.1.31.1.1.1.7.187 .1.3.6.1.2.1.31.1.1.1.7.187 .1.3.6.1.2.1.31.1.1.1.10.399 .1.3.6.1.2.1.31.1.1.1.7.399 .1.3.6.1.2.1.31.1.1.1.7.399 .1.3.6.1.2.1.31.1.1.1.6.399 .1.3.6.1.2.1.31.1.1.1.6.142 .1.3.6.1.2.1.31.1.1.1.10.142 .1.3.6.1.2.1.31.1.1.1.7.142 .1.3.6.1.2.1.31.1.1.1.7.142 .1.3.6.1.2.1.31.1.1.1.7.215 .1.3.6.1.2.1.31.1.1.1.7.215 .1.3.6.1.2.1.31.1.1.1.6.215 .1.3.6.1.2.1.31.1.1.1.10.215 .1.3.6.1.2.1.31.1.1.1.7.112 .1.3.6.1.2.1.31.1.1.1.6.112 .1.3.6.1.2.1.31.1.1.1.10.112 .1.3.6.1.2.1.31.1.1.1.7.112 .1.3.6.1.2.1.31.1.1.1.10.139 .1.3.6.1.2.1.31.1.1.1.7.139 .1.3.6.1.2.1.31.1.1.1.7.139 .1.3.6.1.2.1.31.1.1.1.6.139 .1.3.6.1.2.1.31.1.1.1.7.111 .1.3.6.1.2.1.31.1.1.1.7.111 .1.3.6.1.2.1.31.1.1.1.6.111 .1.3.6.1.2.1.31.1.1.1.10.111 .1.3.6.1.2.1.31.1.1.1.7.486 .1.3.6.1.2.1.31.1.1.1.6.486 .1.3.6.1.2.1.31.1.1.1.10.486 .1.3.6.1.2.1.31.1.1.1.7.486 .1.3.6.1.2.1.31.1.1.1.10.394 .1.3.6.1.2.1.31.1.1.1.7.394 .1.3.6.1.2.1.31.1.1.1.7.394 .1.3.6.1.2.1.31.1.1.1.6.394 .1.3.6.1.2.1.31.1.1.1.6.338 .1.3.6.1.2.1.31.1.1.1.10.338 .1.3.6.1.2.1.31.1.1.1.7.338 .1.3.6.1.2.1.31.1.1.1.7.338]
SNMP (10.241.254.11) get error: Unable to decode packet: nil
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x415962]

goroutine 1 [running]:
main.(*InfluxMeasurement).GetSnmpData(0xc820014cd0, 0xc820162300, 0x1, 0x0, 0x0, 0x0)
        /root/grafana-lab/src/github.com/paulstuart/influxsnmp/snmpmetric.go:350 +0x1272
main.(*SnmpDeviceCfg).Init(0xc8201ac000, 0xc820156f55, 0x12)
        /root/grafana-lab/src/github.com/paulstuart/influxsnmp/snmpdevice.go:246 +0x2ce6
main.init.1()
        /root/grafana-lab/src/github.com/paulstuart/influxsnmp/main.go:158 +0x5fe
main.init()
        /root/grafana-lab/src/github.com/paulstuart/influxsnmp/web.go:282 +0x4f0

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        /usr/lib/golang/src/runtime/asm_amd64.s:1696 +0x1
```

You can see the crashing code here: ( https://github.com/toni-moreno/influxsnmp/blob/first_big_refactor/snmpmetric.go#L342 )

Can you help me to debug this panic please?

**Comment by toni-moreno** [comment]
I've uploaded the generated debug file to this gist, if you need some more info.
https://gist.github.com/toni-moreno/40dc6353127fbd21828afc6108699100

**Comment by wdreeveii** [comment]
According to that dump, the SNMP agent is responding with error TooBig with
nothing supplied in the VBL.

@codedance

https://github.com/soniah/gosnmp/blame/master/marshal.go#L282

Are we sure an empty VBL is an error of this magnitude?

On Mon, Apr 11, 2016 at 8:08 AM, Toni Moreno <notifications@github.com>
wrote:

> I've uploaded the generated debug file to this gist, if you need some more
> info.
> https://gist.github.com/toni-moreno/40dc6353127fbd21828afc6108699100
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/soniah/gosnmp/issues/62#issuecomment-208428828>
>



-- 
Whitham D. Reeve II
907-764-5263

**Comment by soniah** [comment]
Hi everyone, I'm having laser surgery on my eyes tomorrow - better vision :-) But that means I'll be taking a break for two weeks from programming :-/

**Comment by toni-moreno** [comment]
Hi @soniah how are you ? I'm done a workaround by changing snmpget to snmpgetbulk method to get indexed OID's, but only working with snmp version > 2 , whould like to fix this error for old snmp version 1 devices.

Thanks a lot!

**Comment by wdreeveii** [comment]
Soniah, what do you want to do about this? I often have to use SNMPV1 for ... reasons. I am likely to be affected by this at some point. 

We could try removing the check to allow code higher up the opportunity to deal with it. Need to verify by looking through the call graph. Does that seem like a good idea to you?

**Comment by soniah** [comment]
Hi @wdreeveii , I've had a look through the code and don't understand the implications - but I'm at a campsite with mosquitos and a flat laptop :-)

I've been trying to understand the effect of removing this:

(line 282)
```go
len(result.Variables) < 1
```
ie if *unmarshal* returns a SnmpPacket with no Variables, why it is a problem. 

A call graph on v1 protocol would be handy, I can't remember the protocol differences between v1 & v2c

**Comment by schotlandzegtja** [comment]
This relates to the issue I opened #72 

My issue was more around allowing the specification of the maximum OIDs requested but the error still goes unhandled from what I can see in the code.

Is there anything ongoing currently to support SNMP error codes returned from the remote agent?

**Comment by soniah** [comment]
I'm not sure. At the moment I'm focussing on the trap code.

**Comment by soniah** [comment]
Notes for myself:
- Max oids exceeded is now handled (eg *gosnmp.go*, line 310).
- returned SNMP error codes....?

**Comment by soniah** [comment]
Closing as stale. @toni-moreno please log a new issue if this is still relevant.
