### ISSUE TITLE
gonsmp.Counter32 real type ( int32 / uint ) ?

### ISSUE THREAD

**Issue by toni-moreno** [soniah/gosnmp#67]
Hi @soniah 

I've coded an easy pdu2int64 conversor , here.

https://github.com/toni-moreno/snmpcollector/blob/master/pkg/snmp.go#L13

On my devices are working ok but there is some reported crash  here.

https://github.com/toni-moreno/snmpcollector/issues/1#issuecomment-228956383

Could be posible that gnsmp.Gauge32 pdu's has diferent types (int32 in my devices and uint on other devices ) depending the OID or the device?

thank you very much!

**Comment by toni-moreno** [comment]
Acording this document

http://cuddletech.com/articles/snmp/node9.html

Counter32 should be uint32 rather than int32 or uint ... what's the correct type?

I'm really confused with data types now.

**Comment by soniah** [comment]
Hi Toni, you've got 3 issues open and I'd like to help you get them closed - can you provide some direction or pull requests? :-) It's a bit hard for me to keep on top of all the open issues...

Issue https://github.com/soniah/gosnmp/issues/67
Issue https://github.com/soniah/gosnmp/issues/62
Issue https://github.com/soniah/gosnmp/issues/61

@toni-moreno @wdreeveii

**Comment by toni-moreno** [comment]
Sorry @Sonia by the late response, rigth now  I'm not at home , I'm in holidays. I'll come back next week and I'll be able to review all my opened issues. Thank you very much for your patience

**Comment by toni-moreno** [comment]
Hi @soniah I've finally build a workaround for the type conversion and Is now working ok.

https://github.com/toni-moreno/snmpcollector/commit/bf119b0b47757b8b55bce4ad042a67f769ec5b08

I will close this issue and will continue working on these other

**Comment by soniah** [comment]
Thank you @toni-moreno
