### ISSUE TITLE
Use struct members instead of arguments to struct methods

### ISSUE THREAD

**Issue by phemmer** [soniah/gosnmp#71]
The code has several places where a struct has a method which takes arguments that are also struct members.

For example: https://github.com/soniah/gosnmp/blob/f6904fd235070fe56e2c2d799ac5f5862fc32543/marshal.go#L253

    packetOut.marshalMsg(pdus, packetOut.PDUType, msgID, reqID)

The obvious one is `packetOut.PDUType`. The `marshalMsg` method already has access to `packetOut.PDUType` because they are both members of the same struct (`SnmpPacket`).
However all the others can be removed as well.
* `pdus` - `SnmpPacket` has a `Variables` member which should be used instead.
* `msgID` - `SnmpPacket` has a `MsgID` member
* `reqID` - `SnmpPacket` has a `RequestID` member

Numerous other methods are used the same way:
* `marshalSnmpV3ScopedPDU`
* `prepareSnmpV3ScopedPDU`
* `marshalPDU`
* `marshalVBL`

Another example, `(*GoSNMP).GetBulk(oids []string, nonRepeaters uint8, maxRepetitions uint8)`.
The `GoSNMP` struct has `NonRepeaters` and `MaxRepetitions` members. Why, if we're not going to use them?

Aside from not being proper go, these make the code very confusing to follow. And in that last case, confusing to use.

**Comment by wdreeveii** [comment]
We are willing to accept small/isolated pull requests to fix issues like
these. :)

On Sun, Jul 10, 2016 at 9:20 PM, Patrick Hemmer <notifications@github.com>
wrote:

> The code has several places where a struct has a method which takes
> arguments that are also struct members.
>
> For example:
> https://github.com/soniah/gosnmp/blob/f6904fd235070fe56e2c2d799ac5f5862fc32543/marshal.go#L253
>
> packetOut.marshalMsg(pdus, packetOut.PDUType, msgID, reqID)
>
> The obvious one is packetOut.PDUType. The marshalMsg method already has
> access to packetOut.PDUType because they are both members of the same
> struct (SnmpPacket).
> However all the others can be removed as well.
>
>    - pdus - SnmpPacket has a Variables member which should be used
>    instead.
>    - msgID - SnmpPacket has a MsgID member
>    - reqID - SnmpPacket has a RequestID member
>
> Numerous other methods are used the same way:
>
>    - marshalSnmpV3ScopedPDU
>    - prepareSnmpV3ScopedPDU
>    - marshalPDU
>    - marshalVBL
>
> Another example, (*GoSNMP).GetBulk(oids []string, nonRepeaters uint8,
> maxRepetitions uint8).
> The GoSNMP struct has NonRepeaters and MaxRepetitions members. Why, if
> we're not going to use them?
>
> Aside from not being proper go, these make the code very confusing to
> follow. And in that last case, confusing to use.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/soniah/gosnmp/issues/71>, or mute the thread
> <https://github.com/notifications/unsubscribe/AApLwad8CtsCSW9xQuK_vggnQAxCsHioks5qUdKwgaJpZM4JJChO>
> .
>



-- 
Whitham D. Reeve II
907-764-5263

**Comment by soniah** [comment]
Hi Patrick @phemmer thanks for your great suggestions. Would you be able to have a go at this? It seems a smaller task than https://github.com/soniah/gosnmp/issues/70 :-)

**Comment by wdreeveii** [comment]
Many instances of this has been fixed. If you see others please let us know.
