### ISSUE TITLE
snmp connection Return Value Problems

### ISSUE THREAD

**Issue by xuesongbj** [soniah/gosnmp#74]
In the connect function is performed by a connection：

x.Conn, err = net.DialTimeout("udp", addr, x.Timeout)
if err != nil {
    return fmt.Errorf("Error establishing connection to host: %s\n", err.Error())
}

When using net.DialTimeout ( "udp", addr, x.Timeout) connection, if the ip address is unable to connect, does not return an error message. But returns nil

**Comment by soniah** [comment]
Thank you, one of us will investigate.

**Comment by soniah** [comment]
This is a standard use of **net.DialTimeout()**, are you expecting something different?
