### ISSUE TITLE
can't get correct value of "hrSystemDate", if the oid is about  date, the result would not be got.

### ISSUE THREAD

**Issue by FengDe** [soniah/gosnmp#76]
do you have any solution?

**Comment by soniah** [comment]
Thanks Feng, would you mind doing a packet capture? Use the Linux snmp tool and Wireshark. Please place the packet capture on Dropbox or similar.

**Comment by soniah** [comment]
Difficult to understand bug without a proper English description, so closing until a packet capture is provided.
