### ISSUE TITLE
Excess results in bulkwalk

### ISSUE THREAD

**Issue by hh-h** [soniah/gosnmp#78]
When I'm trying to BulkWalk oid ".1.3.6.1.2.1.4.22.1.2.1" I'm getting excess results

```
...
.1.3.6.1.2.1.4.22.1.2.1.10.11.44.254 - correct
.1.3.6.1.2.1.4.22.1.2.1.10.90.90.99 - correct
.1.3.6.1.2.1.4.22.1.2.115.10.198.224.1 - excess
.1.3.6.1.2.1.4.22.1.2.115.10.198.224.3 - excess
...
```

That's how I've fixed it in alouca's gosnmp https://github.com/hh-h/gosnmp/commit/a84b137b46fc707baef573108cbcc86a459e6db8
So I think it'll be enough only add same logic in https://github.com/soniah/gosnmp/blob/master/walk.go#L61 ?
`if !strings.HasPrefix(v.Name, rootOid + string(".")) {`
Because in original netsnmp code oid is array of ints

**Comment by wdreeveii** [comment]
What happens when v.Name == rootOid ? Should I special case that condition?

**Comment by hh-h** [comment]
No, It's impossible. But there's comes one more "bug". You can't call snmpbulkall with final oid.

```
go run main.go
rootOid .1.3.6.1.2.1.2.2.1.20.8 v.Name: .1.3.6.1.2.1.2.2.1.20.9
```

```
snmpbulkwalk -Cc -v 2c -c COMM IP .1.3.6.1.2.1.2.2.1.20.8
iso.3.6.1.2.1.2.2.1.20.8 = Counter32: 0
```

**Comment by wdreeveii** [comment]
The interesting thing about this bug is that net-snmp simply performs another get request when the initial get bulk doesn't return the requested oid.

00:21:49.825008 IP (tos 0x0, ttl 64, id 60369, offset 0, flags [DF], proto UDP (17), length 73)
    localhost.43460 > localhost.snmp: [bad udp cksum 0xfe48 -> 0x0147!]  { SNMPv2c { GetBulk(30) R=1842458018  N=0 M=10 system.9.1.2.1 } } 
00:21:49.825194 IP (tos 0x0, ttl 64, id 60370, offset 0, flags [DF], proto UDP (17), length 336)
    localhost.snmp > localhost.43460: [bad udp cksum 0xff4f -> 0xd6a7!]  { SNMPv2c { GetResponse(289) R=1842458018  system.9.1.2.2=S:snmpUsmMIB.usmMIBConformance.usmMIBCompliances.1 system.9.1.2.3=S:snmpFrameworkMIB.snmpFrameworkMIBConformance.1.1 system.9.1.2.4=S:1 system.9.1.2.5=S:16.2.2.1 system.9.1.2.6=49 system.9.1.2.7=ip system.9.1.2.8=50 system.9.1.2.9=S:13.3.1.3 system.9.1.2.10=92 system.9.1.3.1="The MIB for Message Processing and Dispatching." } } 
00:21:49.825256 IP (tos 0x0, ttl 64, id 60371, offset 0, flags [DF], proto UDP (17), length 73)
    localhost.43460 > localhost.snmp: [bad udp cksum 0xfe48 -> 0x0a4c!]  { SNMPv2c { GetRequest(30) R=1842458019  system.9.1.2.1 } } 
00:21:49.825330 IP (tos 0x0, ttl 64, id 60372, offset 0, flags [DF], proto UDP (17), length 82)
    localhost.snmp > localhost.43460: [bad udp cksum 0xfe51 -> 0xcdfa!]  { SNMPv2c { GetResponse(39) R=1842458019  system.9.1.2.1=S:snmpMPDMIB.snmpMPDMIBConformance.snmpMPDMIBCompliances.1 } }

**Comment by wdreeveii** [comment]
hh, db6b5e552bd4a5 will fix this last issue - to behave more like net-snmp.

I am having a real problem duplicating this issue. Can you send me a pcap file? That will help write a test for this condition.

**Comment by hh-h** [comment]
Unfortunately I can't, sorry! But I'll tell you how to test it!
Install snmpd
add to /etc/snmp/snmpd.conf
```
rocommunity public  localhost
extend .1.3.6.1.4.555.6 hi5 /bin/echo "555.6"
extend .1.3.6.1.4.555.5 hi6 /bin/echo "555.5"
extend .1.3.6.1.4.555.66 hi66 /bin/echo "555.66"
```
Now you're ready to check it
` snmpbulkwalk -On -Cc -v 2c -c public localhost 1.3.6.1.4.555`

` snmpbulkwalk -On -Cc -v 2c -c public localhost 1.3.6.1.4.555.6` will return results for 66 also, but shouldn't!
```
/ # snmpbulkwalk -On -Cc -v 2c -c public localhost 1.3.6.1.4.555.6
.1.3.6.1.4.555.6.1.0 = INTEGER: 1
.1.3.6.1.4.555.6.2.1.2.3.104.105.53 = STRING: "/bin/echo"
.1.3.6.1.4.555.6.2.1.3.3.104.105.53 = STRING: "\"555.6\""
.1.3.6.1.4.555.6.2.1.4.3.104.105.53 = ""
.1.3.6.1.4.555.6.2.1.5.3.104.105.53 = INTEGER: 5
.1.3.6.1.4.555.6.2.1.6.3.104.105.53 = INTEGER: 1
.1.3.6.1.4.555.6.2.1.7.3.104.105.53 = INTEGER: 1
.1.3.6.1.4.555.6.2.1.20.3.104.105.53 = INTEGER: 4
.1.3.6.1.4.555.6.2.1.21.3.104.105.53 = INTEGER: 1
.1.3.6.1.4.555.6.3.1.1.3.104.105.53 = STRING: "555.6"
.1.3.6.1.4.555.6.3.1.2.3.104.105.53 = STRING: "555.6"
.1.3.6.1.4.555.6.3.1.3.3.104.105.53 = INTEGER: 1
.1.3.6.1.4.555.6.3.1.4.3.104.105.53 = INTEGER: 0
.1.3.6.1.4.555.6.4.1.2.3.104.105.53.1 = STRING: "555.6"
```

I think that's better than pcap file :)

**Comment by hh-h** [comment]
Added example of script to test and output

**Comment by soniah** [comment]
Appears to be fixed by https://github.com/soniah/gosnmp/commit/db6b5e552bd4a54e1692046a03b4dd8682cdcd6f Closing

**Comment by hh-h** [comment]
No, it's not fixed yet,

**Comment by hh-h** [comment]
@soniah please reopen
