### ISSUE TITLE
SNMPV3 usm traps do not initialize/update AuthoritativeEngineId/Boots/Time

### ISSUE THREAD

**Issue by wdreeveii** [soniah/gosnmp#80]
Please correct me if I am wrong, but the AuthoritativeEngine Id, AuthoritativeEngineBoots, and AuthoritativeEngineTime parameters in the SNMPV3 USM are not initialized and maintained when sending traps. I believe this is an expectation of an SNMPV3 USM agent.

Also, byte for byte, how well do GoSNMP trap packets match those emitted from other libraries?

**Comment by soniah** [comment]
Stale, closing. Please re-open if required.
