### ISSUE TITLE
Empty octet strings yield non-empty byte slices with a null (0x00) character in them

### ISSUE THREAD

**Issue by madari** [soniah/gosnmp#82]
Octet strings with no content (e.g. set sysLocation to "" in snmpd.conf) yield Go byte slices with a null-byte 0x00 in them.

This is wrong: the result should be an empty (or nil) byte slice p, such that len(p) == 0. I tried snmpget and WapSNMP and both seem to handle this correctly.

**Comment by wdreeveii** [comment]
I am sort of conflicted by this. My understanding is that WapSNMP simply converts this to a string to avoid the null character. If you convert it back to a []byte, it still contains the null character. Principally an OctetString is not a string, but a length prefixed byte array, and GoSNMP will dutifully return the contents of the field to you. (The justification for this is easy ... encrypted data which may contain null values is regularly passed as an OctetString before decryption).

I am inclined to say that if you want this behaviour, simply cast the value to a string your self. I am going to leave this open for a while to solicit comments from others.

**Comment by madari** [comment]
I think my bug title may have been misleading. This is about empty octet strings, i.e. asnlength == 0: GoSNMP translates an empty octet string into a non-empty byte array.

Go strings are not null terminated, so I don't understand what you mean by "WapSNMP simply converts this to a string to avoid the null character".

**Comment by wdreeveii** [comment]
I could not duplicate with my snmpd setup, but please try the latest commit and report back.

**Comment by madari** [comment]
Seems to work as expected now! Thanks for the quick fix.
