### ISSUE TITLE
unmarshalV3Header panic

### ISSUE THREAD

**Issue by sbowman** [soniah/gosnmp#87]
TrapListeners for SNMP v3 panic when trying to parse the V3 header.  It looks like this line in v3.go in unmarshalV3Header is trying to access the SecurityParameters without initializing them (SecurityParameters is a reference to an interface):

```
cursor, err = response.SecurityParameters.unmarshal(response.MsgFlags, packet, cursor)
```

**Comment by soniah** [comment]
@wdreeveii ? v3 is your baby ;-)

**Comment by soniah** [comment]
Stale, closing. Please re-open if required.
