### ISSUE TITLE
SendTrap fails with "Unable to parse OID"

### ISSUE THREAD

**Issue by sbowman** [soniah/gosnmp#88]
You prepend the timetick PDU to the front of the PDUs list with a blank Name.  When you try to marshal that, the marshaler can't handle a blank OID.

**Comment by wdreeveii** [comment]
Hello Sean,

As you can see trap support is in alpha/beta state, so thanks for these issues. While the fixes for these are straightforward, I will need a little more time to write tests.

**Comment by soniah** [comment]
Thanks @sbowman, and thanks @wdreeveii (for everything in general...)
