### ISSUE TITLE
How to avoid Out Of Order Errors ?

### ISSUE THREAD

**Issue by toni-moreno** [soniah/gosnmp#89]
Hi @soniah .

We have some troubles to get BulkData as @vkosilko report us in:  https://github.com/toni-moreno/snmpcollector/issues/11

The problem seems to be here:

https://github.com/toni-moreno/snmpcollector/blob/master/pkg/influxmeasurement.go#L309

could be a configuration issue? could be a gosnmp issue? There is any Snmp Configuration , action to take or workaround to avoid this error? 

Thank you very much.

**Comment by toni-moreno** [comment]
After some investigation I've solved changing BulkWalkAll for BulkWalk(). 
Thank you very much

**Comment by yusufozturk** [comment]
@toni-moreno we also have same problem. how did you solve the issue? Could you share your BulkWalk function?

Thanks.

**Comment by sumitroajiprabowo** [comment]
same issue. 
ERROR out of order
Walk, BulkWalk and BulkWalkAll method if duplicated request at same time..
