### ISSUE TITLE
Acting as SNMP agent?

### ISSUE THREAD

**Issue by thom-nic** [soniah/gosnmp#90]
Apologies in advance but could this library be used to act as an agent, e.g. listen and respond to incoming SNMP GET and SET requests?  I see sending traps is supported which is great.  Thanks!

**Comment by wdreeveii** [comment]
GoSNMP will not act as a SNMP agent at this time. Pull requests are welcome!

**Comment by soniah** [comment]
@thom-nic the library can act as an agent, see `SendTrap` in `trap.go`. Is this what you're looking for?

**Comment by thom-nic** [comment]
@soniah sending traps is part of it, yes.  But also listening for and responding to incoming Get, GetNext and Set SNMP requests.  I opted to use [node-snmpjs](https://github.com/joyent/node-snmpjs) instead.
