### ISSUE TITLE
Generated lots of logs in /var/log/messages for WALK

### ISSUE THREAD

**Issue by sapamja** [soniah/gosnmp#91]
Hi,

This is not an issue but I would like to know how to prevent it.
When I used gosnmp/walk it generated lots of logs for all the subtree in /var/log/messages. But when I used unix command snmpwalk it doesn't generate verbose logs except one line of logs for the UDP connection.

Here is the verbose logs when i used gosnmp:

        send response:
        snmpd[2734]:     -- HOST-RESOURCES-MIB::hrSWInstalledDate.600
        send response:
        snmpd[2734]:     -- HOST-RESOURCES-MIB::hrSWInstalledDate.601

Is there a way to mute this logs on the server side.

thanks sapamja

**Comment by wdreeveii** [comment]
GoSNMP does not log to /var/log/messages unless you told it to, perhaps by passing a logger instance to it.

If you can't find the required level of verbosity with the way things are currently logged, we welcome a patch to add this capability.

**Comment by soniah** [comment]
Thanks @sapamja for your issue, it looks like I can close it.
