### ISSUE TITLE
Resource Pooling

### ISSUE THREAD

**Issue by rjrobinson** [soniah/gosnmp#96]
So, i have a slight issue. Im wondering if anyone has had the same. 

I have been senting GET's to some addresses, and I noticed that at scale, 1/2 of the requests fail. Im guessing that this is due to a time out, or the port isnt open for sending requests. 

Im looking at spinning up go routines ( about 100k requests at a time ) to reset things. 

Anyone have any thoughts about this. I'm not even sure how to test this.

**Comment by wdreeveii** [comment]
@rjrobinson Did your investigation reveal anything interesting?

**Comment by soniah** [comment]
Closing 'no reply'
