### ISSUE TITLE
Support contexts for timeouts

### ISSUE THREAD

**Issue by brian-brazil** [soniah/gosnmp#97]
For https://github.com/prometheus/snmp_exporter/ we're doing bulk walks of mulitple OIDs, which can take some time. It'd be useful to have an overall timeout on the all walks, as well as knowing quickly if a device is simply down so we can fail fast.

I propose to add support for contexts for timeouts to make this cleaner, and likely also doing something around the retry logic so that this all remains sane.

**Comment by soniah** [comment]
Hi @brian-brazil , you've possibly forgotten about this. I close it for now as "not enough time from me". Pull requests welcome, and I'll reopen 👍

**Comment by brian-brazil** [comment]
I've not forgotten, but I've not much time myself either :)

**Comment by soniah** [comment]
Ok, one day we'll all have time :-) Re-opening.

**Comment by Malik0117** [comment]
I want to use your package gosnmp. But I don't know, how to use it. I'm not programmer so Can you help me ?

**Comment by soniah** [comment]
Hi Malik.

Please have a look at the examples, in the folder called 'examples'. If you don't know how to program, I suggest you start with something like [Learn how to Code: Google Go](https://www.udemy.com/learn-how-to-code/) or [LearnPython](https://www.learnpython.org/).

**Comment by Malik0117** [comment]
Hi Soniah, 
Thank you for your Help. :)

**Comment by soniah** [comment]
I'm going to close this. Contexts are [contentious](https://faiface.github.io/post/context-should-go-away-go2/), adding them would require large changes, and application developers are able to code for this using [existing Go features](https://gobyexample.com/select).

**Comment by soniah** [comment]
See vma's work

**Comment by dswarbrick** [comment]
Any chance of releasing a v1.23.1 tag with this included? I just ran into build failures trying to package the latest snmp_exporter for Debian, and realised that an updated 1.23.0 gosnmp package won't help either.

**Comment by soniah** [comment]
There you go - 1.23.1 and 1.24.0 tagged. Enjoy :-)

**Comment by soniah** [comment]
I believe `CHANGELOG.md` is in Debian format, though I'm not sure and I don't know if it helps packaging...
