### ISSUE TITLE
tooBig snmp error not logged ?

### ISSUE THREAD

**Issue by toni-moreno** [soniah/gosnmp#98]
Hi @wdreeveii @soniah . We have an Issue to our snmpcollector tool  related to the "tooBig" error returned when doing bulkwalk over certain devices. ( https://github.com/toni-moreno/snmpcollector/issues/161)

IMHO this error is saying us that we should change our Max-repetition config but we can not tune it if there is not any error message with this "tooBig" ,  message . Isn't it? Thus when debug enabled the output has no this error  ( https://github.com/toni-moreno/snmpcollector/issues/161#issuecomment-290982571).

I suggest adding check for this kind of error, or pass the SnmpPacket info to the walk function.

Thanx a lot!

**Comment by wdreeveii** [comment]
Can you provide details on how to reproduce this?

**Comment by soniah** [comment]
Closing as stale - there's only so many hours in my life :-) @toni-moreno please open a new issue if this is still relevent .
